### ISSUE TITLE
ERROR  [monitor.py:382] (200, ('192.168.25.96', 80))

### ISSUE THREAD

**Issue by rerpires** [liaan/broadlink_ac_mqtt#101]
Hi, 

Running Docker here. (installed with network HOST) 
Mosquitto Docker also. 

##########
root@ac2mqtt:/app/ac2mqtt# ./monitor.py -d
Starting Monitor...
(200, ('192.168.25.96', 80))
Stopping
root@ac2mqtt:/app/ac2mqtt#
###########

########
2022-09-26 02:22:35,834,834 DEBUG    [monitor.py:284] ./monitor.py v1.1.1 is starting up
2022-09-26 02:22:35,834,834 DEBUG    [monitor.py:286] Loglevel set to DEBUG
2022-09-26 02:22:35,840,840 DEBUG    [monitor.py:138] Checking if already running
2022-09-26 02:22:35,840,840 INFO     [monitor.py:342] Starting Monitor...
2022-09-26 02:22:35,840,840 DEBUG    [monitor.py:344] Starting mainloop, responding on only events
2022-09-26 02:22:35,841,841 DEBUG    [AcToMqtt.py:304] Coneccting to MQTT: 192.168.25.56 with client ID = ac_to_mqtt
2022-09-26 02:22:35,842,842 DEBUG    [ac_db.py:343] Debugging Enabled
2022-09-26 02:22:35,842,842 DEBUG    [ac_db.py:347] Authenticating
2022-09-26 02:22:35,842,842 DEBUG    [AcToMqtt.py:553] Mqtt connected! client=<paho.mqtt.client.Client object at 0x7fc62ef06ed0>, userdata=None, flags={'session present': 0}, rc=0
2022-09-26 02:22:35,842,842 DEBUG    [AcToMqtt.py:558] Listing on /aircon/+/+/set for messages
2022-09-26 02:22:35,843,843 DEBUG    [AcToMqtt.py:275] publishing on topic "/aircon/LWT", data "online"
2022-09-26 02:22:36,844,844 DEBUG    [monitor.py:381] Traceback (most recent call last):
  File "./monitor.py", line 352, in start
    devices = AC.make_device_objects(config['devices'])
  File "/app/ac2mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 76, in make_device_objects
    device_objects[device['mac']] = broadlink.gendevice(devtype=0x4E2a, host=(device['ip'],device['port']),mac = bytearray.fromhex(device['mac']), name=device['name'],update_interval = self.config['update_interval'])
  File "/app/ac2mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 19, in gendevice
    return ac_db(host=host, mac=mac,name=name, cloud=cloud,devtype= devtype,update_interval = 0)
  File "/app/ac2mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 348, in __init__
    if self.auth() == False:
  File "/app/ac2mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 176, in auth
    response = self.send_packet(0x65, payload)
  File "/app/ac2mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 258, in send_packet
    raise ConnectTimeout(200,self.host)
ConnectTimeout: (200, ('192.168.25.96', 80))

2022-09-26 02:22:36,844,844 ERROR    [monitor.py:382] (200, ('192.168.25.96', 80))
2022-09-26 02:22:36,844,844 INFO     [monitor.py:169] Stopping
##############

root@ac2mqtt:/app/ac2mqtt# ping 192.168.25.96
PING 192.168.25.96 (192.168.25.96): 56 data bytes
64 bytes from 192.168.25.96: seq=0 ttl=255 time=45.957 ms
64 bytes from 192.168.25.96: seq=1 ttl=255 time=66.268 ms
64 bytes from 192.168.25.96: seq=2 ttl=255 time=92.238 ms

any idea ? 

Thank you

**Comment by liaan** [comment]
Hi, 

make sure your wifi allows client to client communication (not isolated clients) .. also check that nothing else is trying to connect to the aircon (mobile app etc) as the AC's are often to slow to speak to both and times out

the easiest normally to test the wifi is to use the auto discovery , if don't detect the AC, you either have network issue, or not compatible AC

**Comment by rerpires** [comment]
> Hi,
> 
> make sure your wifi allows client to client communication (not isolated clients) .. also check that nothing else is trying to connect to the aircon (mobile app etc) as the AC's are often to slow to speak to both and times out
> 
> the easiest normally to test the wifi is to use the auto discovery , if don't detect the AC, you either have network issue, or not compatible AC

Hi Liaan, 

Docker is configured with HOST network, but nevertheless I tried deploying a new Ubuntu Server in another VM to make sure it is in the same broadcast domain. Same result. 

The AC is 3 meters from an Access-point, and looking at the ICMP that I sent I believe it is not a radio issue. 

I used NMAP to search for open ports on this unit and in fact it's UDP/80. 

The AC is provisioned in the APP AC Freedom, but I was not using it ate the same time as I was running monitor.py 

Do you see any troubleshoot that I can do ? Is there a way that I can send direct payload to the AC or something ? 

Thank you !

**Comment by f0rb1dd3n403** [comment]
Hi, I have the same exact behaviour. PING works fine. Is this something related with the new AC Freedom APP?
I read that someone was able to fix the issue by interrupting the wifi association procedure just after the app sent WIFI credentials, but this does not work for me. 

The module installed on climate is bl3353-p.... 

Any suggestion?

**Comment by liaan** [comment]
Hi.    Nmap on port 80 UDP will always be fine as udp is a one-way communication. so it won't know if port is open or not.. its fire and forget protocol

Almost always if discovery don't work its either network isolation is enabled on the wifi "router" or firewall somewhere blocking things.   the host and AC must be on the same broadcast domain as it sends packet to 255.255.255.255 to find devices. 

if discovery works, but you get authentication failed, then i believe you need todo that wifi disconnect hack before app is finished.

So just check if discovery work  (./monitor.py -S)  , it should dump the device/s found

The aircons uses broadlink protocol, and there is few apps/script you can also try to discover the device, might not be able to control it.. but might help with troubleshooting.

its very possible things have changed since wrote this.   I to be honest..  my system works, so there was never any need to try get things to work on new aircons.   Was always hopeing someone else might take over who has new AC's.

L:

**Comment by f0rb1dd3n403** [comment]
Hi Liian, thank you for your reply. Yes, udp check on port 80 is listed as filtered, so no way to understand if devices reply properly. Unfortunately discovery mode doesn't work for me: no devices found.. devices are in the same network segment and I can catch broadcast requests on a separate client running tcpdump when i run monitor.py -S. 

So the main guess could be that devices are not compatible. Maybe those are locked to communicate only towards a cloud endpoint, as I can see from a tcpdump on the router... they send tcp packets on 1885 port of a remote host.

I hope someone in the near future could find a workaround. Otherwise I have to rely on a IR device (sob).
The air conditioner brand is ARGO by the way.

**Comment by liaan** [comment]
can you do sniff on phone (android normally allowes it)  and see what ports are used to talk from the argo app ?

**Comment by f0rb1dd3n403** [comment]
Very hard to do so with iPhone. The app is AC Freedom. I need to connect to the AP exposed by the air conditioner first… then the AC freedom sends Wi-Fi credential to the device. After that I need to connect the iPhone to the same network and the app is able to bind the device to the cloud.

**Comment by liaan** [comment]
did you try the disconnect before last step hack ?   i've never done it, so not sure how it works..  I don't even have ac freedom installed anymore so cannot help with that.

**Comment by f0rb1dd3n403** [comment]
yes.... tried many times interrupting at different stages.. No luck..
as soon as I finish work I will try to share my experience with home assistant geeks just to understand if what I did can produce some insight and maybe find a solution within the community.

Thank you so much for your help. Maybe in the future someone reading this post will share their experiences that could help to solve the issue.

**Comment by liaan** [comment]
> 

Hi

Are you still struggling with this?   I have some time now and planning to rewrite the pluging to work direct out of Hass and try get program the AC without the app

not sure if you intersted in helping?  if so.. can you possibly join the telegram group for easier chats?  https://t.me/+1Xw9Kwr2P7k2YjY0

**Comment by f0rb1dd3n403** [comment]
Happy to help

**Comment by maeek** [comment]
Hi, I also encountered this exact problem and would like to help

**Comment by Maximus48p** [comment]
Also running the docker version as host.

```
Starting Monitor...
(200, ('192.168.1.34', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.34', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.34', 80))
Stopping
```

Logging from MQTT Docker
```
2022-12-19T19:30:00: New connection from 172.29.111.1:54635 on port 1883.
2022-12-19T19:30:00: New client connected from 172.29.111.1:54635 as ac_to_mqtt (p2, c1, k60, u'mqtt').
2022-12-19T19:30:00: Will message specified (7 bytes) (r0, q1).
2022-12-19T19:30:00: 	/aircon/LWT
2022-12-19T19:30:00: Sending CONNACK to ac_to_mqtt (0, 0)
2022-12-19T19:30:00: Received SUBSCRIBE from ac_to_mqtt
2022-12-19T19:30:00: 	/aircon/+/+/set (QoS 0)
2022-12-19T19:30:00: ac_to_mqtt 0 /aircon/+/+/set
2022-12-19T19:30:00: Sending SUBACK to ac_to_mqtt
2022-12-19T19:30:00: Received PUBLISH from ac_to_mqtt (d0, q0, r1, m0, '/aircon/LWT', ... (6 bytes))
2022-12-19T19:30:00: Sending PUBLISH to mqtt-explorer-17fa2416 (d0, q0, r0, m0, '/aircon/LWT', ... (6 bytes))
2022-12-19T19:30:01: Received DISCONNECT from ac_to_mqtt
2022-12-19T19:30:01: Client ac_to_mqtt disconnected.
```


I have read somewhere that it could be related to python version???
But i have no clue what that means.

**Comment by thecode** [comment]
> Also running the docker version as host.
> 
> ```
> Starting Monitor...
> (200, ('192.168.1.34', 80))
> Stopping
> Starting Monitor...
> (200, ('192.168.1.34', 80))
> Stopping
> Starting Monitor...
> (200, ('192.168.1.34', 80))
> Stopping
> ```
> 
> Logging from MQTT Docker
> 
> ```
> 2022-12-19T19:30:00: New connection from 172.29.111.1:54635 on port 1883.
> 2022-12-19T19:30:00: New client connected from 172.29.111.1:54635 as ac_to_mqtt (p2, c1, k60, u'mqtt').
> 2022-12-19T19:30:00: Will message specified (7 bytes) (r0, q1).
> 2022-12-19T19:30:00: 	/aircon/LWT
> 2022-12-19T19:30:00: Sending CONNACK to ac_to_mqtt (0, 0)
> 2022-12-19T19:30:00: Received SUBSCRIBE from ac_to_mqtt
> 2022-12-19T19:30:00: 	/aircon/+/+/set (QoS 0)
> 2022-12-19T19:30:00: ac_to_mqtt 0 /aircon/+/+/set
> 2022-12-19T19:30:00: Sending SUBACK to ac_to_mqtt
> 2022-12-19T19:30:00: Received PUBLISH from ac_to_mqtt (d0, q0, r1, m0, '/aircon/LWT', ... (6 bytes))
> 2022-12-19T19:30:00: Sending PUBLISH to mqtt-explorer-17fa2416 (d0, q0, r0, m0, '/aircon/LWT', ... (6 bytes))
> 2022-12-19T19:30:01: Received DISCONNECT from ac_to_mqtt
> 2022-12-19T19:30:01: Client ac_to_mqtt disconnected.
> ```
> 
> I have read somewhere that it could be related to python version??? But i have no clue what that means.

That's can't be related to Python version, when you are using Docker the Python is part of the image. I have the same error, this is probably due to new devices either having a different protocol or locked.

**Comment by Maximus48p** [comment]
![image](https://user-images.githubusercontent.com/38084877/208501552-75d7db0a-69ea-414e-b02f-d67d09fdfc67.png)

These are sold under different names. Cheap airco's with Broadlink wifi module.
Works with Freecom AC app. Bought recently, so pretty new indeed.

Anything i can do to help?

**Comment by thecode** [comment]
There is a discussion about it here: https://community.home-assistant.io/t/broadlink-ac-integration-ac-freedom-aux-dunham-rcool-akai-rinnai-kenwood-tornado-ballu/342789/71

**Comment by liaan** [comment]
> Also running the docker version as host.
> 
> ```
> Starting Monitor...
> (200, ('192.168.1.34', 80))
> Stopping
> Starting Monitor...
> (200, ('192.168.1.34', 80))
> Stopping
> Starting Monitor...
> (200, ('192.168.1.34', 80))
> Stopping
> ```
> 
> Logging from MQTT Docker
> 
> ```
> 2022-12-19T19:30:00: New connection from 172.29.111.1:54635 on port 1883.
> 2022-12-19T19:30:00: New client connected from 172.29.111.1:54635 as ac_to_mqtt (p2, c1, k60, u'mqtt').
> 2022-12-19T19:30:00: Will message specified (7 bytes) (r0, q1).
> 2022-12-19T19:30:00: 	/aircon/LWT
> 2022-12-19T19:30:00: Sending CONNACK to ac_to_mqtt (0, 0)
> 2022-12-19T19:30:00: Received SUBSCRIBE from ac_to_mqtt
> 2022-12-19T19:30:00: 	/aircon/+/+/set (QoS 0)
> 2022-12-19T19:30:00: ac_to_mqtt 0 /aircon/+/+/set
> 2022-12-19T19:30:00: Sending SUBACK to ac_to_mqtt
> 2022-12-19T19:30:00: Received PUBLISH from ac_to_mqtt (d0, q0, r1, m0, '/aircon/LWT', ... (6 bytes))
> 2022-12-19T19:30:00: Sending PUBLISH to mqtt-explorer-17fa2416 (d0, q0, r0, m0, '/aircon/LWT', ... (6 bytes))
> 2022-12-19T19:30:01: Received DISCONNECT from ac_to_mqtt
> 2022-12-19T19:30:01: Client ac_to_mqtt disconnected.
> ```
> 
> I have read somewhere that it could be related to python version??? But i have no clue what that means.

it should work on all python versions .   unless 2.x broke now with latest itteration

just do monitor.py -S to see if things discovered
then make sure you have same config in config file and check the mqtt host
