### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by Ellargo333** [liaan/broadlink_ac_mqtt#103]
Hi, i'm having the following issue when I try to start the container. What does Errno -3 means?

I use Mosquitto as the MQTT

ac2mqtt  | [cont-init.d] 10-adduser: exited 0.
ac2mqtt  | [cont-init.d] 30-config: executing...
ac2mqtt  | **** Config file not found, copying sample config ****
ac2mqtt  | **** Newer version found. Grabbing latest code ****
ac2mqtt  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
ac2mqtt  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14  100    14    0     0     19      0 --:--:-- --:--:-- --:--:--    19
ac2mqtt  | tar: This does not look like a tar archive
ac2mqtt  | gzip: invalid magic
ac2mqtt  | tar: Child returned status 1
ac2mqtt  | tar: Error is not recoverable: exiting now
ac2mqtt  | **** Updating versions ****
ac2mqtt  | [cont-init.d] 30-config: exited 0.
ac2mqtt  | [cont-init.d] 99-custom-files: executing...
ac2mqtt  | [custom-init] no custom files found exiting...
ac2mqtt  | [cont-init.d] 99-custom-files: exited 0.
ac2mqtt  | [cont-init.d] done.
ac2mqtt  | [services.d] starting services
ac2mqtt  | [services.d] done.
ac2mqtt  | Starting Monitor...
ac2mqtt  | [Errno -3] Try again
ac2mqtt  | Stopping
ac2mqtt  | Starting Monitor...
ac2mqtt  | [Errno -3] Try again
ac2mqtt  | Stopping
ac2mqtt  | Starting Monitor...
ac2mqtt  | [Errno -3] Try again
ac2mqtt  | Stopping
ac2mqtt  | Starting Monitor...
ac2mqtt  | [Errno -3] Try again
ac2mqtt  | Stopping
ac2mqtt  | Starting Monitor...

**Comment by Ellargo333** [comment]
I was able to sort that out, but now:


ac2mqtt  | Starting Monitor...
ac2mqtt  | something went wrong, no devices found

**Comment by liaan** [comment]
Hi,   Can you log the docker issues under the docker repo so the docker person can try help, I don't look after docker (and have 0 idea how works)
