### ISSUE TITLE
Feature Request: Adjustable power limit for AUX conditioner

### ISSUE THREAD

**Issue by rumunn95** [liaan/broadlink_ac_mqtt#104]
Please add the ability to set the power consumption limit as in acfreedom from 30% to 100% this is a great option to create heating automation in home assistant in the case of converting the air conditioner into an air heat pump.

**Comment by liaan** [comment]
Hi, 
Sorry, I don't have access to Aux AC's.  so cannot do this .

You can always do a full debug logging and check the packets getting logged while setting this value, and see which bits/bytes get changed.

**Comment by rumunn95** [comment]
This is very sad news😭😭, unfortunately I'm a bit green in the subject and I don't think I can do it

**Comment by liaan** [comment]
haha..   everyone green at some point .. just depends on how geek you want to get trying to get things to work
