### ISSUE TITLE
'int' object has no attribute 'title'

### ISSUE THREAD

**Issue by xinstein** [liaan/broadlink_ac_mqtt#107]
Here's an illustrative part of the log

```
Starting Monitor...
(200, ('{my ac ip}', 80))
Stopping
Starting Monitor...
'int' object has no attribute 'title'
Stopping
Starting Monitor...
(200, ('{my ac ip}', 80))
Stopping
Starting Monitor...
(200, ('{my ac ip}', 80))
Stopping
Starting Monitor...
(200, ('{my ac ip}', 80))
Stopping
Starting Monitor...
'int' object has no attribute 'title'
Stopping
Starting Monitor...
(200, ('{my ac ip}', 80))
Stopping
Starting Monitor...
'int' object has no attribute 'title'
Stopping
Starting Monitor...
'int' object has no attribute 'title'
Stopping
Starting Monitor...
(200, ('{my ac ip}', 80))
Stopping
Starting Monitor...
```

In the code I searched "title" and found only this line: 
https://github.com/liaan/broadlink_ac_mqtt/blob/bbc9c26a1299aac72ee68a718e88277ff95185d4/broadlink_ac_mqtt/classes/broadlink/ac_db.py#L854

Seems hard to figure out the reason for this error with neither familiarity of your code nor a workable debug environment.

Sincerely hope you can help me resolve this

**Comment by liaan** [comment]
hi, 

the fact you seeing the my ac ip means you having other issues..     

please paste the output of "./monitor.py -S"

regarding the debug environment.  run with debug flag and check log files

**Comment by xinstein** [comment]
I use HAOS (the official vdi image) setup.
I've poked around for a while, can't seem to find the entrance for the add-ons container

**Comment by liaan** [comment]
> I use HAOS (the official vdi image) setup. I've poked around for a while, can't seem to find the entrance for the add-ons container

Huh?

Sorry,  don't understand,  did you install it by using Git and setup cron etc.. or is it someone elses wrapper loading this script?

Either way ..   

Try git clone of this repo .. then paste the output of ./monitor.py -S .. I need to see if your aircons are getting detected.
