### ISSUE TITLE
Tornado x not discovered

### ISSUE THREAD

**Issue by orxelm** [liaan/broadlink_ac_mqtt#109]
Hi
My tornados are connected and i can see them on my router client list as "AC_SMT-XX-XX-XX"
But when running the script i get "No devices found"

**Comment by thecode** [comment]
There is a long discussion about it here: https://community.home-assistant.io/t/broadlink-ac-integration-ac-freedom-aux-dunham-rcool-akai-rinnai-kenwood-tornado-ballu/342789

I have a similar AC, it looks like this device is locked during provisioning, you can get additional information in the link above, there is also a group trying to reverse engineer this behaviour.

**Comment by liaan** [comment]
yup.

alot of new device is cloud locked.  we busy trying to see if we can get the protocol decoded to try and unlock it.. I just have to many things on my plate.. so might take while still

in mean time going to try get the cloud api decoded, think few guys hacked that already, so one can at least control it via that till lan is unlocked

**Comment by orxelm** [comment]
@thecode can you help me join the group to try reverse engineer the local protocol ?

**Comment by thecode** [comment]
I am not the owner of the group, in https://community.home-assistant.io/t/broadlink-ac-integration-ac-freedom-aux-dunham-rcool-akai-rinnai-kenwood-tornado-ballu/342789/64 there is a link to the Telegram group
