### ISSUE TITLE
Error when one device is unavailable or offline

### ISSUE THREAD

**Issue by ArtemVladimirov** [liaan/broadlink_ac_mqtt#110]
I have three air conditioners in my configuration, if you turn off at least one air conditioner from electricity, the program will reboot forever and the rest of the air conditioners will be unavailable in home assistant.

**Comment by liaan** [comment]
Sounds about right,  it simply loops through all the devices in the config file, if any fails, it might or might not work.  its not programmed for failure.   you are welcome to add error checking and do a PR ;-)

Would suggest to make 3 instances then, each monitoring 1 AC,  just make sure to check where the duplicate runtime file is stored so they won't prevent each other from starting
