### ISSUE TITLE
Suggestion: MQTT Messaging Change

### ISSUE THREAD

**Issue by mrjemson** [liaan/broadlink_ac_mqtt#17]
Seems MQTT auth issue is resolves and I can manually enter device details instead of relying on auto discover now which is great.

One suggestion, it is crazy chatty on the MQTT front. Can you add a config flag to only publish messages on change? Just store the values as a local variable and publish if the polled value is different to that of the stored variable?

Also want to confirm, to turn on would the value be: aircon/MAC/power/set ON ?
Doesn't seem to work for me.

Might be cool to set up a discord or something to allow for exchange of ideas and test results instead of via git issues also.

**Comment by wjbeckett** [comment]
while we wait for @liaan to create a Discord - I have set one up here in the meantime.
https://discord.gg/fwjCpU

**Comment by liaan** [comment]
@mrjemson 
Chatty?  :-) you should see what my MQTT looks like , this script is quite ...

I will see how difficult it is to create a "on change" system,  might have code somewhere already..  Python is not my first language so takes some time to create new code

RE power command
```
elif function == "power":
			if value.lower() == "on":
				status = self.device_objects[address].switch_on()
				if status :
					self.publish_mqtt_info(status)
			elif value.lower() == "off":
				status = self.device_objects[address].switch_off()
				if status :
					self.publish_mqtt_info(status)
			else:
				logger.debug("Switch on has invalid value, values is on/off received %s",value)
				return
```
