### ISSUE TITLE
Begin adding releases/tags

### ISSUE THREAD

**Issue by wjbeckett** [liaan/broadlink_ac_mqtt#18]
Would be great if you can start pushing releases. My docker build script uses tags to grab the latest code. Currently I'm using my GitHub repo to keep everything up to date but would like to use the official.

**Comment by liaan** [comment]
Cool.  I'm happy.. just need to google how (rofl) .. For someone who does Dev for living i'm pretty useless with all the new things ...  stuck in my old ways

**Comment by liaan** [comment]
@Backslashh   Can I close?

**Comment by wjbeckett** [comment]
Yep!
