### ISSUE TITLE
Climate devices show up as unnamed in HA

### ISSUE THREAD

**Issue by wjbeckett** [liaan/broadlink_ac_mqtt#19]
The autodiscovery between monitor.py and Home assistant is working really well, however the devices appear as `climate.unnamed_device` in Home-Assistant and you aren't able to edit the entity_id.

It's fine for the devices to show up as unnamed, but we need to be able to change the entity_id.

**Comment by liaan** [comment]
@Backslashh 
Sorry, I don't know Home-Assist at all (just installed it to get the autodiscovery tested), can you please give me indication where I can see this?

**Comment by wjbeckett** [comment]
Yeah sure,
Join Discord chanel here and we can chat a bit better.
https://discord.gg/fwjCpU

**Comment by liaan** [comment]
Defaulting to mac if no name found
closing
