### ISSUE TITLE
Traceback and ImportError

### ISSUE THREAD

**Issue by talondnb** [liaan/broadlink_ac_mqtt#2]
Hi,

I'm getting the following error when trying to run the script:

Traceback (most recent call last):
  File "./monitor.py", line 28, in <module>
    import ac_db as broadlink
  File "././ext/broadlink/ac_db.py", line 5, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

Any idea how I can fix this? Running on MacOS 10.12.

**Comment by liaan** [comment]
Did you download the EXT folder and put it same folder as the monitor.py script?

**Comment by talondnb** [comment]
Yes, I grabbed the whole repo. It seems to be an issue with my Python install perhaps, I'm trying to sort this now and will post my results.

**Comment by talondnb** [comment]
Unfortunately I'm not savvy enough to get this going, it seems to use deprecated python modules and i have no idea what i'm doing. Trying to figure out how to get python2 installed as the script uses the deprecated 'commands' module and also pycrypto?

**Comment by talondnb** [comment]
Ok I've managed to get this running, but nothing happens and I get the following if I break the script:

iMac:broadlink_ac_mqtt-master andrewmunday$ python2 monitor.py 
^CTraceback (most recent call last):
  File "monitor.py", line 262, in <module>
    main()
  File "monitor.py", line 255, in main
    q = AcToMqtt()		
  File "monitor.py", line 70, in __init__
    time.sleep(5)
KeyboardInterrupt

Also, how do I specify username and password for my MQTT broker?

**Comment by liaan** [comment]
hi, 
Try run it with -d options .. python2 monitor.py -d   it should then log to file in the same folder: error.log with full debuuging

you can do tail -f error.log& to keep eye on the log file realtime

**Comment by liaan** [comment]
Regarding MQTT user/password .. no idea , will need to check code, I don't use Auth MQTT here

**Comment by talondnb** [comment]
Thanks for the suggestion. It looks like things are working but it's not discovering the AC. The Kelvinator AC I'm using broadcasts itself as BL-xx-xx-xx and based on the data stored on my phone through the Kelvinator app, it uses Broadlink cloud. I thought this might be able to pick it up but I guess not! Thanks liaan, if you ever need a guinea pig for this model, let me know. :)

**Comment by talondnb** [comment]
Ok so I had more of a play and turns out this script requires you to be on the same subnet as the AC (I have my IoT stuff on a separate VLAN). I'm getting something else now:

```
DEBUG:__main__:./monitor.py v0.001 is starting up
DEBUG:__main__:Loglevel set to DEBUG
DEBUG:__main__:Starting mainloop, responding on only events
DEBUG:__main__:Coneccting to MQTT: 10.10.10.12
DEBUG:__main__:Connecting to host
DEBUG:__main__:our client id (and also topic) is abc
Traceback (most recent call last):
  File "./monitor.py", line 262, in <module>
    main()
  File "./monitor.py", line 255, in main
    q = AcToMqtt()		
  File "./monitor.py", line 45, in __init__
    if device.devtype == 0x4E2a:
AttributeError: device instance has no attribute 'devtype'

```

**Comment by liaan** [comment]
morning
Yes, need be same broadcast subnet as it works on broadcast ... PIA .  You might be able to create custom broadcast rule if you switch is capible.

It could be that the ID is different so not finding the AC in the list of "known" devices.    if you dig into the EXT folder library there is somewhere where it matches the discovered device to the list.

**Comment by liaan** [comment]
Did you come right, can I close issue?

**Comment by liaan** [comment]
Stale, closing
