### ISSUE TITLE
HEX command question

### ISSUE THREAD

**Issue by makleso6** [liaan/broadlink_ac_mqtt#41]
Hi
How do you create hex code for command? https://github.com/liaan/broadlink_ac_mqtt/blob/master/broadlink_ac_mqtt/classes/broadlink/ac_db.py#L549
What soft or application do you use?

**Comment by liaan** [comment]
Morning.

my secret :)

I use a combination of wireshark and android studio debugging ... some developers do lot of debugging info while developing and forget to switch it of when pushing to production, so you get lot of inside info using the debugging output.
