### ISSUE TITLE
Device name in hass auto discovery

### ISSUE THREAD

**Issue by mrekin** [liaan/broadlink_ac_mqtt#43]
Hi.
Trying to add my AUX conditioner with broadlink module to home assistant with your code.
HASS discovery works (with set of tasmota devices) and discovery topic is right.
I setup broadlink_ac_mqtt for discovery, I see config in target topic but hass not catch it.

The second problem is: "name" parameter is "config" message is empty (looks  problem with encoding/decoding in code) - I simply add hardcode in ActoMqtt.py with device name to check if this is stopper for autodiscovery..but no.

Thanks.

**Comment by mrekin** [comment]
Just tested with configured manually: hass show current state, temp and other, but control not working.

**Comment by liaan** [comment]
Hi, 
Sorry, what is AUX conditioner?  Lots of devices use the broadlink "network protocol" and discover, but don't mean they use same protocol for communication.

also, can you run it with the -d flag and check the output in the error.log .. it should print all the debugging info.

**Comment by mrekin** [comment]
"AUX" is a brand name :) Model - ASW-H09A4/DE-R1DI . And now intalled "non original" wifi module (host name: BroadLink_OEM-T1-c3-cf-90)
With -d flag i see only log/out.log. This log does not contain any error messages, only DEBUG messages (a lot of  [AcToMqtt.py:93] Timeout 10 not done..
and less
[ac_db.py:517] Acinfo Raw Response:
[ac_db.py:518] Acinfo Raw Hex:
[ac_db.py:533] AcInfo:
)
Nothing new happens in log then I press  buttons in home assistant climate card (but it show current state of device - if I start it by IR remote or APP - home assistant shows actual mode and temperature.

**Comment by mrekin** [comment]
_AcToMqtt.py
->def _on_mqtt_connect(self, client, userdata, flags, rc):
--> "sub_topic"_ 
is hardcoded (and my mistake to test not with default values :) )

Now I see error messages
2020-07-06 07:55:16,431,431 DEBUG    [AcToMqtt.py:289] Mqtt Message Received! Userdata: None, Message tele/aircon/24dfa7c3cf90/mode_homeassistant/set b'off'
2020-07-06 07:55:16,431,431 DEBUG    [AcToMqtt.py:295] Mqtt decoded --> Function: mode_homeassistant, Address: b'24dfa7c3cf90', value: b'off'
2020-07-06 07:55:16,431,431 DEBUG    [AcToMqtt.py:281] Mqtt logCaught exception in on_message: b'24dfa7c3cf90'

**Comment by liaan** [comment]
Can you please post your config file and run monitor.py with the -d flag. then post the full output of your error.log (all the debug) .
 Just want to see what is found/not found. 
Might be the unit don't work with the script

**Comment by mrekin** [comment]
[AUXbroadlink.zip](https://github.com/liaan/broadlink_ac_mqtt/files/4877190/AUXbroadlink.zip)

Zip contains config, log and -S option output.
Conditioner was started\stopped by IR remote (you can see thouse operations in log), then I try to start it from hass ("Mqtt logCaught exception" in log).
Now hardcoded "device name" and fixed "sub_topic".

**Comment by liaan** [comment]
when you hardcode, you will have to hardcode the name in a lot of places.....

I see your config have the devices at the bottom, but you still have **self_discovery** set to **true** at the top. Set the self discovery to **false**, then it will use the device settings as specified under devices (its one or the other)

not sure why your name shows "binary" .. it suppose to show the name or fallback to Mac address.  I'll check the code

let me know if the MQTT works with the self_discovery set to false and **_without_** any hardcoding.

**Comment by mrekin** [comment]
I will check later.
I'm not clear with a python, but i found possible error point
`def _on_mqtt_message(self, client, userdata, msg):
-> status = self.device_objects[address].set_homeassistant_mode(value) ` 
     address and value as I see in debug is byte arrays. They compared later in code with str and exception occured.
     I change it with
`-> status = self.device_objects[address.decode("utf-8")].set_homeassistant_mode(value.decode("utf-8"))
`	 
and it seems working!

**Comment by mrekin** [comment]
I set self_discovery to "false", topic_prefix to "/aircon" and get fresh install.
- name correcly publishing from config to mqtt topic
- mqtt autodiscovery works fine
- comands from hass still cause 
`2020-07-06 12:00:56,831,831 DEBUG    [AcToMqtt.py:291] Mqtt decoded --> Function: mode_homeassistant, Address: b'24dfa7c3cf90', value: b'fan_only'
2020-07-06 12:00:56,831,831 DEBUG    [AcToMqtt.py:277] Mqtt logCaught exception in on_message: b'24dfa7c3cf90'
`
I use Python3.6

So 2 problems are: subsciption topic are hardcoded  and commands cause exceptions (looks like incorrect types in '==' statement.
And some debug messages cope&pasted, seems need to fix ("Fanspeed on has invalid value" in AcToMqtt.py)

**Comment by liaan** [comment]
mmm.. though that hardcoded subscribe topic was fixed .. will do when have a gap

please send then whole debug again, missing the relavant part of the debug to assist you with the MQTT issue.

Are you running a non english OS ?

**Comment by mrekin** [comment]
[out_new.zip](https://github.com/liaan/broadlink_ac_mqtt/files/4878061/out_new.zip)
I missed to stop service, so out.log a little big :)
No, only en_US locale is OS. I had a some bugs with ru_ locale at past, so now use only one locale.

```
user@smarthome:~$ uname -a
Linux smarthome 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
user@smarthome:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```
Google  says that Python3 do not convert byte array automatically to str in comparition statements (Python2 does), so looks problem described above exists.

upd: I tried to change device name in "AC Freedom" - it was cyrillic, but -S option returns the same "name: !!binary "" "

**Comment by liaan** [comment]
do you have python2.7 installed maybe? if so can you try run it on that, then at least we know is python3 issue (python2.7 ./monitor.py)

I think its problem with the string encoding when reading the config file vs string encoding reading the mqtt address.  probably why when you do the .utf-8 it works

I'll startup my HA machine (only have it for DEV) and will try do some testing on python3.6 .. I know it works fine on python 2.7.18.

**Comment by mrekin** [comment]
No, I haven't python2.7.  
Debug shows we try to compare b'' value with string values. This works in Python2x and not in Python3x. I think this is not encoding issue.
`https://stackoverflow.com/questions/30580386/why-does-comparison-of-bytes-with-str-fails-in-python3`

**Comment by liaan** [comment]
its actually not "comparing" .  The devices array is using "STR" for elements, but the name from mqtt topic was encoded to byte array.  This used to be interchangable in python2 (as per your link) .  

Why it works on some is that your mac address starts with a "numeric" and python then things its byte array, and it seems like most others mac address start with a  "letter" so it things its a string.

I forced it to make it a string always (I hope).

Please pull the latest version (1.0.13) and test again

**Comment by mrekin** [comment]
[out_1.log](https://github.com/liaan/broadlink_ac_mqtt/files/4879018/out_1.log)
Nope..

**Comment by liaan** [comment]
well, we 1 step further .. now bomming on the value of mqtt
will force to string as well

**Comment by liaan** [comment]
pull and test again please .. should be 1.0.13a

**Comment by liaan** [comment]
having bugs in latest push .. will let you know just now when resolved

**Comment by liaan** [comment]
ok, tested it on Python 3.8.2 and seems to be working now

**Comment by mrekin** [comment]
I works now!  Thanks a lot.
Still not fixed
`sub_topic = "/aircon/+/+/set"` :)
and some debug messages.. :)

**Comment by liaan** [comment]
> I works now! Thanks a lot.
> Still not fixed
> `sub_topic = "/aircon/+/+/set"` :)
 

think fixed

**Comment by mrekin** [comment]
Yes, fixed.
