### ISSUE TITLE
Python 2.7 - unicode error

### ISSUE THREAD

**Issue by danstr1** [liaan/broadlink_ac_mqtt#45]
Hi,

With the latest version there is a bug when running in python 2.7 (and that is the one in the docker of Backslash) (https://github.com/broadlink-ac/broadlink_ac_mqtt_docker)

It only happen when trying to shutdown\change mode (changing temp is working fine)
In the log I see this line:
2020-07-09 14:14:28,496,496 DEBUG    [ac_db.py:461] Status variable is not string <type 'unicode'>

I try to go to an older version (git checkout tags/1.12a) and in that version it is back to work fine

BTW, I try to run in python3 and all is working good, so maybe I will ask backslashh to update the version of python in the docker?

**Comment by danstr1** [comment]
BTW, 

Sometimes (even that all is working great) I get this error message: "bytearray index out of range"
I try to debug it and found that it came from line 538 in classes/broadlink/ac_db.py
It seems that sometimes my AC seems to response with messages that are under 15 byte
If I add something like this:
 **if len(response_payload) > 15:**
                     ##Its only the last 5 bits?
                     self.status['ambient_temp'] = response_payload[15] & 0b00011111
It cause it to stop showing the error and seems that the functionality is still work without errors..

**Comment by liaan** [comment]
@danstr1   Sorry, should have tested pyhton2.7 as well.   I'll check bit later and get this sorted. There was change between 2.7 and 3 regarding detection of strings "types" (byte array  vs Str) so one have to force one or the other to make work in both versions.

Also will add the check for response length...

**Comment by liaan** [comment]
@danstr1   Can you please do monitor.py -v for me on the one that crashes.  The latest version is working correclty for me on python2.7 and 3.   (Monitor Version: 1.0.13b, Class version:1.0.2)

**Comment by danstr1** [comment]
Monitor Version: 1.0.13b, Class version:1.0.2

Maybe there is problem with the name of one AC (it doesn't recognized it well if I run with -S)
I think that originally his name in the official app was not in English so maybe that cause to the problem, but now it is in English but maybe it take the origin name? (anyway, I don't need the names, as I use HA and it send the topics by MAC)
- ip: 192.168.1.54
  mac: 34ea34dcf2d6
  name: ''
  port: 80

Thanks

**Comment by liaan** [comment]
> 
> 
> Monitor Version: 1.0.13b, Class version:1.0.2
> 
> Maybe there is problem with the name of one AC (it doesn't recognized it well if I run with -S)
> I think that originally his name in the official app was not in English so maybe that cause to the problem, but now it is in English but maybe it take the origin name? (anyway, I don't need the names, as I use HA and it send the topics by MAC)
> 
>     * ip: 192.168.1.54
>       mac: 34ea34dcf2d6
>       name: ''
>       port: 80
> 
> 
> Thanks

If you specify name in the config and disable autodiscovery it uses the name in the config (in theory) . I actually did not test this .. let me check

**Comment by liaan** [comment]
flip .. I should read the errors ...

I see its a different error than I thought.    Let me check again

**Comment by danstr1** [comment]
I try give it a name and disable the auto discovery but same issue:
2020-07-10 13:26:15,815,815 DEBUG    [ac_db.py:461] Status variable is not string <type 'unicode'>

**Comment by liaan** [comment]
I'm just starting up my HA to test better .. the latest version (1.14b) should might work..

**Comment by danstr1** [comment]
Still not work :(
2020-07-10 13:39:08,396,396 DEBUG    [ac_db.py:461] Status variable is not string <type 'unicode'>

root@raspberrypi:/opt/docker-compose/apps/ac2mqtt/git/broadlink_ac_mqtt# ./monitor.py -v
Monitor Version: 1.0.14b, Class version:1.0.2

**Comment by liaan** [comment]
WTF.  i hate python
