### ISSUE TITLE
run broadlink_ac_mqtt on HassOS

### ISSUE THREAD

**Issue by najjadasm** [liaan/broadlink_ac_mqtt#49]
Greetings,

How can I run broadlink_ac_mqtt on my network by home assistant OS.

There any mothod to run broadlink_ac_mqtt  all time like in AppDaemon addone

**Comment by liaan** [comment]
Hi, 

Simplest is to run setup a cron to trigger start of monitor.py every minute .. The script checks if already running to so won't create multiples

There is also a docker version, if you prefer docker:  https://github.com/broadlink-ac/broadlink_ac_mqtt_docker
