### ISSUE TITLE
MQTT Authentication

### ISSUE THREAD

**Issue by mrjemson** [liaan/broadlink_ac_mqtt#5]
Doesn't look like MQTT auth works despite the user/password fields in the config.
I see this was mentioned in Issue #2 but can't see if it was fixed.

**Comment by liaan** [comment]
> Doesn't look like MQTT auth works despite the user/password fields in the config.
> I see this was mentioned in Issue #2 but can't see if it was fixed.

Morning
Config file was only introduced this week, its still very much hack.   Focus currently is to get the service to be stable with different aircons.

I will add this options to config soon.

**Comment by liaan** [comment]
> Doesn't look like MQTT auth works despite the user/password fields in the config.
> I see this was mentioned in Issue #2 but can't see if it was fixed.

Auth now working.  (I think)
