### ISSUE TITLE
Turbo and mute

### ISSUE THREAD

**Issue by SirGeorg** [liaan/broadlink_ac_mqtt#50]
How to turn on turbo mode or mute?

**Comment by liaan** [comment]
Hi, Was thinking this morning when someone going to ask for this :-)

This is all the functions the class can do, currently most of them is not implemented. the * is ones that already work.
Let me know which ones you would like, then I can add them
```
['temp'] *
['ambient_temp'] *
['power'] *
['fanspeed']  *
['mode']  *
['fixation_v'] 
['sleep'] = 
['display'] 
['mildew'] 
['health'] 
['fixation_h'] 
['ifeel'] 
['mute'] 
['turbo']
['clean'] 

```

**Comment by SirGeorg** [comment]
Thank you very much for the quick response and your work! I need only ['mute'] and ['turbo'] :-)

**Comment by liaan** [comment]
> Thank you very much for the quick response and your work! I need only ['mute'] and ['turbo'] :-)

cool
I'll try do bit later today otherwise tommorrow

Do you need to have it work on HASSIO or just MQTT?

**Comment by SirGeorg** [comment]
I think just MQTT. I don't understand this well, but i have built docker container using Dockerfile and requirements.txt. Now it works well in docker on raspbian

**Comment by liaan** [comment]
Hallo, i'm having issue with the mute function, seems to have stopped working.. I'll get sorted over weekend/monday.  

Also, there is docker version already:  https://github.com/broadlink-ac/broadlink_ac_mqtt_docker maintained by @Backslashh  .

**Comment by wjbeckett** [comment]
My docker container is somewhat "official". 
It will auto-update when new code is pushed from this repo and is multi-arch as well so it's built for everything really.

**Comment by liaan** [comment]
@SirGeorg 

Do you want mute (no beep beep) , or silent (as button on remote) ?

**Comment by SirGeorg** [comment]
Silent. This is problem? :-)

**Comment by liaan** [comment]
> Silent. This is problem? :-)

Nope .. Just need to figure it out.  I thought mute and silent same thing, but seem to be different.

**Comment by wjbeckett** [comment]
Mute on my remote is really low fan speed.

**Comment by liaan** [comment]
@SirGeorg 

I did not forget, hectic week...

**Comment by liaan** [comment]
~~Mute~~ 
```
 Mosquitto_pub -h mqtt.wonderland.internal -t "/aircon/b4430da741af/mute/set" -m "OFF" 
Mosquitto_pub -h mqtt.wonderland.internal -t "/aircon/b4430da741af/mute/set" -m "ON"  

```

~~Turbo~~ 
```
  mosquitto_pub -h mqtt.wonderland.internal -t "/aircon/b4430da741af/turbo/set" -m "ON"
 mosquitto_pub -h mqtt.wonderland.internal -t "/aircon/b4430da741af/turbo/set" -m "OFF" 

```

**Comment by liaan** [comment]
Pondering, probably should move the turbo and mute commands to fan speed, cause its as @Backslashh  said, just fan speed settings....

**Comment by wjbeckett** [comment]
> Pondering, probably should move the turbo and mute commands to fan speed, cause its as @Backslashh  said, just fan speed settings....

Yeah probably a good idea.
That's how they are represented in AC Freedom app (as fan speeds)

**Comment by liaan** [comment]
Moved turbo and mute to fanspeeds
```
mosquitto_pub -h mqtt.wonderland.internal -t "/aircon/b4430da741af/fanspeed/set" -m "TURBO"
mosquitto_pub -h mqtt.wonderland.internal -t "/aircon/b4430da741af/fanspeed/set" -m "MUTE"
```

**Comment by liaan** [comment]
ag crap, forgot to update the statuses, will do tommorrow

**Comment by liaan** [comment]
ok, think all working now

![image](https://user-images.githubusercontent.com/864607/91854708-6abedf00-ec64-11ea-83db-081f21689fd2.png)
![image](https://user-images.githubusercontent.com/864607/91854757-7d391880-ec64-11ea-91d9-6200f079f14f.png)

**Comment by catalinbordan** [comment]
Yessss!!! it is working if I copy the last changes. thank you thank you. You are great!!!
I have here in Romania a unit of AC called: Vortex (locally branded by Romania vendors) witch has broadlink wifi and work with acFreedom
If if I will figure out how to keep climate entity in HA between restart it will be great. Now I have to stop start monitor. Also a nice feature to have it in HACS or a way to use the same machine where it is HA. Wright now because I am a noobs a have another virtual box with xubuntu to have this monitor running.
Thank you for sharing with us your work.

**Comment by liaan** [comment]
> If if I will figure out how to keep climate entity in HA between restart it will be great. Now I have to stop start monitor. Also a nice feature to have it in HACS or a way to use the same machine where it is HA. Wright now because I am a noobs a have another virtual box with xubuntu to have this monitor running.
> Thank you for sharing with us your work.

in config file, add 
```
 auto_discovery_topic_retain: True
```
see: https://github.com/liaan/broadlink_ac_mqtt/blob/master/settings/config_sample.yml

This will make the MQTT keep the config , and then HA will remember it between restarts (in theory)

**Comment by liaan** [comment]
I fixed the problem where you not able to change name in HA sometimes .. Added unique ID
so hopefully this will also help with remember settings between restarts

![image](https://user-images.githubusercontent.com/864607/91869922-ba0e0b00-ec76-11ea-8694-4fc7edf3caac.png)

**Comment by catalinbordan** [comment]
> This will make the MQTT keep the config , and then HA will remember it between restarts (in theory)

I have it in my config file, but it is not working for me. I need to stop start monitor.py. I will open a new issue to not spam here.

**Comment by catalinbordan** [comment]
> I fixed the problem where you not able to change name in HA sometimes .. Added unique ID
> so hopefully this will also help with remember settings between restarts
> 

Yes, now we can change the name
No, still I have to stop/start monitor.py

**Comment by liaan** [comment]
ja... seeing that as well (restart) .. (headbang).  not making sense  @mrekin got it to work, hopefully he can chirp in .. I can only check again tomorrow.. pizza time

**Comment by catalinbordan** [comment]
> . pizza time

OK, no problem.
pizza? funny also in my mind to buy it.  Bon appetite!

**Comment by mrekin** [comment]
Hi all :) 
`auto_discovery_topic_retain` works for me (HA+mosquitto+ broadlink_ac_mqtt), but not the latest version.
I can check with actual 'bam' later (today or tomorrow - all in my wife hangs :) )

At first - can you 
1. show config part with mqtt settings ?
2. Connect to your mqtt server with some client (like MQTT explorer) and check if messages to discovery topic a retained
![bam_retained](https://user-images.githubusercontent.com/8645868/91881089-a61fd480-ec89-11ea-8bee-0aa71001f313.png)
 
upd: new issue opened :)

**Comment by liaan** [comment]
For HA restart issues see #52  

@SirGeorg  , can I close this ticket for Mute/Turbo?

**Comment by SirGeorg** [comment]
Many thanks! Everything works well!

**Comment by advokatden** [comment]
Good afternoon! Could you add a sleep mode?

**Comment by liaan** [comment]
Hi,

Is that not same as silent ?  or do you maybe know what aircon does in sleep mode?

**Comment by advokatden** [comment]
> Hi, Is that not same as silent ? or do you maybe know what aircon does in sleep mode? From: advokatden ***@***.***> Sent: Monday, 27 June 2022 22:00 To: liaan/broadlink_ac_mqtt ***@***.***> Cc: Karman de Lange ***@***.***>; State change ***@***.***> Subject: Re: [liaan/broadlink_ac_mqtt] Turbo and mute (#50) Good afternoon! Could you add a sleep mode? - Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliaan%2Fbroadlink_ac_mqtt%2Fissues%2F50%23issuecomment-1167821720&data=05%7C01%7C%7C8455e89f9e6a4555e4e808da5877ac73%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637919568346226754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0A2yAwR2NbM1jPI%2Fec5AQoVbcBpe0tdyEUAC2LkfG20%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAGTCX33RDEACKEMPT3EEDLVRIB5PANCNFSM4QGAT6QA&data=05%7C01%7C%7C8455e89f9e6a4555e4e808da5877ac73%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637919568346226754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pGqpVTDR%2FLwLNgqi01BjV7rWbD8OT994tjtmuqHH%2BOY%3D&reserved=0>. You are receiving this because you modified the open/close state.Message ID: ***@***.******@***.***>>

In SLEEP* mode, during cooling operation,
 after the first hour of operation, the set temperature
 automatically increases by 1 °C, after the second
 go - by another 1 ° С.
  Further, the set temperature remains unchanged.
 opinion.
 • In the SLEEP* mode during heating operation,
 after the first hour of operation, the set temperature
 the temperature is automatically lowered by 2 °C,
 after the second - by another 2 ° C.
  Further, the set temperature remains unchanged.
 opinion.
 Main

**Comment by liaan** [comment]
> Good afternoon! Could you add a sleep mode?

Morning

I see the sleep option is actually a command option, have you tried to see if works using mqtt direct?

```
elif function ==  "sleep":	
			try:
				if self.device_objects.get(address):					
					status = self.device_objects[address].set_sleep(value)					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return

```

**Comment by advokatden** [comment]
> mqtt direct

Good afternoon. I used mqtt explorer, and I managed to set sleep mode =on. 
As a temporary solution added in configuration.yaml preset mode

    preset_mode_command_topic: /aircon/a043b08df008/sleep/set
    preset_modes:
      - "ON"
      - "OFF"

The redim turns on, but if you restart HA, the state does not recover

**Comment by liaan** [comment]
Ok, so at least the "function" works

It should send the mqtt state every X seconds (depending on the config), and on each change.

You should be able to add the sleep option in the  device_array = { on line 170 in AcToMqtty.py .. that is the "HA config" that gets published to HA and HA uses for discovery (if I remember correctly).

I assume you enabled the "auto_discovery_topic_retain: " to retain the config for HA ?

**Comment by advokatden** [comment]
> Ok, so at least the "function" works It should send the mqtt state every X seconds (depending on the config), and on each change. You should be able to add the sleep option in the device_array = { on line 170 in AcToMqtty.py .. that is the "HA config" that gets published to HA and HA uses for discovery (if I remember correctly). I assume you enabled the "auto_discovery_topic_retain: " to retain the config for HA ? From: advokatden ***@***.***> Sent: Tuesday, 26 July 2022 10:34 To: liaan/broadlink_ac_mqtt ***@***.***> Cc: Karman de Lange ***@***.***>; State change ***@***.***> Subject: Re: [liaan/broadlink_ac_mqtt] Turbo and mute (#50) mqtt direct Good afternoon. I used mqtt explorer, and I managed to set sleep mode =on. As a temporary solution added in configuration.yaml preset mode preset_mode_command_topic: /aircon/a043b08df008/sleep/set preset_modes: - "ON" - "OFF" The redim turns on, but if you restart HA, the state does not recover - Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliaan%2Fbroadlink_ac_mqtt%2Fissues%2F50%23issuecomment-1195177406&data=05%7C01%7C%7C1cfcf423091641728dd408da6ee1a25d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637944212612550468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YxQyTv1PRWkPyrXmnNbLZ03eCZVCqaKzyk8LzZ79jTE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAGTCX4PWDXIXZCEEM2VQVDVV6PIXANCNFSM4QGAT6QA&data=05%7C01%7C%7C1cfcf423091641728dd408da6ee1a25d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637944212612550468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0GmV%2BoUKh2eZLk1NghrqQXveBgcQOhLjP2fWUYM5RHM%3D&reserved=0>. You are receiving this because you modified the open/close state.Message ID: ***@***.******@***.***>>

Hello.
my config.yml
auto_discovery_topic_retain setting: false

And what should I add to AcToMqtty.py ?
