### ISSUE TITLE
Confirmed working with Ballu BSUI/IN-12HN8

### ISSUE THREAD

**Issue by antonwantstosleep** [liaan/broadlink_ac_mqtt#51]
Hi!

I can confirm working with Ballu BSUI/IN-12HN8 (with intergated Wi-Fi module and AC Freedom app).

I configured everything manually:
- _self_discovery: False_ in config.yml
- _climate entry_ in HA configuration.yaml
- added ac`s IP into firewall block list (in order to block remote access from chinese servers / app)

Everything seems working! Thank you very much!

**Comment by antonwantstosleep** [comment]
Also can I ask you some questions?

1. I use Home Assistant and seems that after restart it loses all information about AC (ambient temp. working mode, etc.). I think it's a "retain" problem - i need to mention _retain: true_ in HA's climate entry in order to make **all** messages retain:
```
##If retain is set for MQTT, then retain it		
		if(self.config["mqtt_auto_discovery_topic_retain"]):
			retain = self.config["mqtt_auto_discovery_topic_retain"]
		else: 
			retain = False
```
Right?

2. If a topic (**temp**, **fanspeed_homeassistant**) has a _value_ and _set_ subtopics, I can set it by a message to topic/set. If a topic (**ifeel**, **clean**, **display** etc.) has only _value_ subtopic - it's only for information, I can't set it. Right?

**Comment by liaan** [comment]
@antonwantstosleep 

Currently the retain is just o that the config stays in HA. It should get latest values within the refresh timeout (default 10 seconds) as the script resends all values every timeout interval (or its suppose to).   

2:   Everything can be set , except ambient temperature.  .... well, suppose to be able to, it was working when I first wrote the script.....  If something don't work, just create issue request and I can look into it.

**Comment by liaan** [comment]
Closing this.
