### ISSUE TITLE
AC ambient temperature

### ISSUE THREAD

**Issue by makleso6** [liaan/broadlink_ac_mqtt#53]
Probably, I found the ambient temperature value after the decimal point
It is not byte offset, and value is on 33 byte. I'll check in AC Freedom app and temp is equal
[34, 0, 187, 0, 7, 0, 0, 0, 24, 0, 1, 33, 224, 129, 0, 7, 125, 57, 81, 81, 81, 100, 41, 40, 87, 57, 60, 16, 174, 240, 0, 0, 0, **8**, 184, 251, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

**Comment by liaan** [comment]
Sorry, you lost me?

**Comment by makleso6** [comment]
What do you mean?)

**Comment by liaan** [comment]
@makleso6  I don't understand your post....

**Comment by makleso6** [comment]
You find solution to get #1 AC ambient temperature in Integer value.
I found AC ambient temperature in Float value.
Sorry my English is no good)

**Comment by liaan** [comment]
aaa . ok .. thanks
I'll have look when I have gap.   So in theory one should get 15.6 vs 15 degrees? (float vs int)

**Comment by makleso6** [comment]
Yes

**Comment by liaan** [comment]
i've not forgotten about your pull requests .. just been swamped

**Comment by liaan** [comment]
Don't work in my aircon ... @Anonym-tsk  , I see you revernse byte 31 and @makleso6 says byte 33.   Can you just confirm works on your aircons?

**Comment by liaan** [comment]
closing for now as no feedback .. will revert to it again in future
