### ISSUE TITLE
Reduce the number of MQTT publishes

### ISSUE THREAD

**Issue by Anonym-tsk** [liaan/broadlink_ac_mqtt#55]
I have one problem.
For example if i set update_interval=5, i have a lot of mqtt messages and a lot of entity updates in Home Assistant.
If i set update_interval=30, number of updates is ok, but i need to wait 30 seconds to get actual AC state.

My idea:
New parameter `mqtt_interval`, for example to send mqtt messages no more than once every `mqtt_interval` seconds or on status update.

With this parameter i will can set update_interval=5 and mqtt_interval=30 and get updates every 5 seconds but send updates to mqtt instantly on state change or once every 30 seconds.

**Comment by liaan** [comment]
This been discussed before.

Aircons don't change enough that one will need 5 second update time, Typical aircon settings change once per day and ambient temperature might change every minute or so, so even 10 seconds update is a overkill.

The problem with short than 10 seconds polling is that some aircons start timing out as they cannot process requests fast enough, especially if you use mobile app as well.  

If you need faster updates when you restart HA, just restart the monitor.py at same time to force refresh, but your HA should not ever restart once its in production.

**Comment by Anonym-tsk** [comment]
Please reopen this issue.
Update interval = 10 seconds is ok. But now with `mqtt_auto_discovery_topic` [force_update](https://github.com/liaan/broadlink_ac_mqtt/blob/36f5cee5569bc91937705e7bf33169787e8552f4/broadlink_ac_mqtt/AcToMqtt.py#L211) is always `True` and i got mqtt message every 10 seconds.
I want to reduce this interval. I want to get data from A/C every 10 seconds but sent it to mqtt if data updated or not more often then once a 60 seconds.

**Comment by liaan** [comment]
Mqtt is made to handle thousands  of messages.  , HA only record if a value has  changed (unless you enabled force_update), so this is not a issue either.

 I cannot see why ~10 values every 10 seconds will cause any issues, can you maybe expand what issues you are experiencing?

**Comment by Anonym-tsk** [comment]
Because if i somewhere use subscription to mqtt topics, i have updates every 10 seconds even if values are not updated really. For example, i use esphome devices and listen mqtt topics there, and i get messages every 10 seconds and need to handle difference on devices.

**Comment by liaan** [comment]
please can we discuss this on discord so others can chip in.  https://discord.gg/Un7FW3X
