### ISSUE TITLE
[Errno -3] Temporary failure in name resolution Stopping

### ISSUE THREAD

**Issue by tyson0941** [liaan/broadlink_ac_mqtt#60]
Hi to all,

   I have a Vortex AC who is using AC Freedom app (and the device type is 0x4e2a) .
  When I use ./monitor.py -S it detects my devices:

xxx@xxx-desktop:~/Desktop/AC$ ./monitor.py -S
*********** start copy below ************
devices:
- ip: 192.168.0.21
  mac: 34ea345b9dd0
  name: ''
  port: 80
- ip: 192.168.0.90
  mac: 34ea344fdeff
  name: ''
  port: 80

*********** stop copy above ************
I have renamed ''config_sample.yml'' to ''config.yml'' and paste it to settings folder  , after I have edited according to my devices settings :

service:
    daemon_mode: True
    update_interval: 10
    self_discovery: True

mqtt:
    host: mqtt
    port: 1883
    client_id: ac_to_mqtt
    user: 
    passwd: 
    topic_prefix: /aircon
    auto_discovery_topic: homeassistant
    auto_discovery_topic_retain: False
    discovery: False

##Devices
devices:
- ip: 192.168.0.21
  mac: 34ea345b9dd0
  name: ''
  port: 80
- ip: 192.168.0.90
  mac: 34ea344fdeff
  name: ''
  port: 80

 And now when I try to run it using ''./monitor.py'' I get this error :  [Errno -3] Temporary failure in name resolution

xxx@xxx-desktop:~/Desktop/AC$ ./monitor.py
Starting Monitor...
[Errno -3] Temporary failure in name resolution
Stopping
xxx@xxx-desktop:~/Desktop/AC$ 

Can someone help me with this error?

**Comment by liaan** [comment]
Morning
Check your MQTT server settings.  Could be the hostname is not resolvable,   Try do ping on the name specified in the config file
