### ISSUE TITLE
Idea aircon on off and on

### ISSUE THREAD

**Issue by cherniavsky94w** [liaan/broadlink_ac_mqtt#62]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/pi/aircon/broadlink_ac_mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 406, in _on_mqtt_message
    status = self.device_objects[address].set_homeassistant_mode(value)
  File "/home/pi/aircon/broadlink_ac_mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 524, in set_homeassistant_mode
    self.set_ac_status()
  File "/home/pi/aircon/broadlink_ac_mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 794, in set_ac_status
    response = self.send_packet(0x6a, request_payload)
  File "/home/pi/aircon/broadlink_ac_mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 242, in send_packet
    response = self.cs.recvfrom(1024)
timeout: timed out
```

**Comment by liaan** [comment]
Hi

This is normal , they aircons are really slow on response so if you query them to fast they simply stop responding.
You will notice this even worst if you have the app on phone open the same time

The monitor.py should continue working, if it don't let me know, will check for you then

**Comment by cherniavsky94w** [comment]
@liaan Thanks
I have some problem, then ac offline and I change his state to on monitor crashing and not responding. Reboot fix this.
monitor work with pm2 with autoreboot
Can you help me?

**Comment by cherniavsky94w** [comment]
I can do this with debug mode

**Comment by liaan** [comment]
@cherniavsky94w  . Monitor should not crash , I'll check that the try/catch is in correct place.

**Comment by cherniavsky94w** [comment]
@liaan thanks!

**Comment by cherniavsky94w** [comment]
@liaan I have new problem
```

0|monitor  | Traceback (most recent call last):
0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 362, in <module>
0|monitor  |     start()
0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 200, in start
0|monitor  |     stop_if_already_running()
0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 95, in stop_if_already_running
0|monitor  |     if(check_if_running()):
0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 140, in check_if_running
0|monitor  |     if (float(contents[1])+ pid_stale_time) < time.time():
0|monitor  | IndexError: list index out of range
```

monitor.py run only with pm2 =(
Comment stop fix it and all work

Maybe I do something wrong, I don't know

**Comment by liaan** [comment]
> @liaan I have new problem
> 
> ```
> 
> 0|monitor  | Traceback (most recent call last):
> 0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 362, in <module>
> 0|monitor  |     start()
> 0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 200, in start
> 0|monitor  |     stop_if_already_running()
> 0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 95, in stop_if_already_running
> 0|monitor  |     if(check_if_running()):
> 0|monitor  |   File "/home/pi/aircon/broadlink_ac_mqtt/monitor.py", line 140, in check_if_running
> 0|monitor  |     if (float(contents[1])+ pid_stale_time) < time.time():
> 0|monitor  | IndexError: list index out of range
> ```
> 
> monitor.py run only with pm2 =(
> Comment stop fix it and all work
> 
> Maybe I do something wrong, I don't know

Sorry, not had time to even think about looking into this issue, hopefully next week is bit less heactic

Can you post your config file and how you starting up the monitor.py .  Maybe I can spot something quickly

**Comment by cherniavsky94w** [comment]
Hi! 
My config:
```
service:
    daemon_mode: True
    update_interval: 10
    self_discovery: True

mqtt:
    host: 172.30.33.0
    port: 1883
    client_id: ac_to_mqtt
    user: hass
    passwd: hass5350
    topic_prefix: /aircon
    auto_discovery_topic: homeassistant
    auto_discovery_topic_retain: False
    discovery: False

devices:
- ip: 192.168.31.9
  mac: 34ea3496bec4
  name: 'Idea Aircon'
  port: 80
```
Start with [pm2 util](https://pm2.keymetrics.io/)
```
pm2 start monitor.py
```

Restart every 5 minutes monitor.py fix it

**Comment by liaan** [comment]
ok, this is something todo with the PID file.

Did this ever resolve itself, if not, what device you running this on?

**Comment by liaan** [comment]
closing no feedback
