### ISSUE TITLE
Can't connect to  AC BSUI-09HN8

### ISSUE THREAD

**Issue by vitaly74** [liaan/broadlink_ac_mqtt#65]
Hello!
I run script:
`python3 ./monitor.py -S
No devices found, make sure you are on same network broadcast segment as device/s`
then I trie connect telnet to port AC:
`telnet 192.168.88.31 80`
Trying 192.168.88.31...
telnet: Unable to connect to remote host: Connection refused

ping ok:
`ping 192.168.88.31`
PING 192.168.88.31 (192.168.88.31) 56(84) bytes of data.
64 bytes from 192.168.88.31: icmp_seq=1 ttl=255 time=1.69 ms
64 bytes from 192.168.88.31: icmp_seq=2 ttl=255 time=1.75 ms
64 bytes from 192.168.88.31: icmp_seq=3 ttl=255 time=1.60 ms

IP I take from  app AC Freedom

Do you know why port is close, and how I can open it?
AC BSUI-09HN8

thank you)

**Comment by liaan** [comment]
Hi, 

If i recall (its been a while since looking at network part) its running UDP and port 80.  So you won't be able to telnet to it.  
it does a broadcast to 255.255.255.255 port 80 to discovery the devices, so just make sure your wifi router allows interconnect between devices and your "pc/server/berry" and the wifi must be on same broadcast network segment and ip broadcast subnet.

**Comment by vitaly74** [comment]
> Hi,
> 
> If i recall (its been a while since looking at network part) its running UDP and port 80. So you won't be able to telnet to it.
> it does a broadcast to 255.255.255.255 port 80 to discovery the devices, so just make sure your wifi router allows interconnect between devices and your "pc/server/berry" and the wifi must be on same broadcast network segment and ip broadcast subnet.

Good day!
Thank you for your answer! if I write the IP of AC in the config file, it also does not work - it  can't connect to AC ((
Have you had any experience with setting up on the basis of microtik?
 Or can you tell me how to diagnose the connection  on broadcast?

**Comment by vitaly74** [comment]
I try this: https://tppr.me/y9Vun ...with default config from git...can you help me -what does it mean 
Starting Monitor...
[Errno -2] Name or service not known ?)

**Comment by liaan** [comment]
Im just on holiday till next week, no access to pc....

Will check when get back

Sorry about delay

________________________________

**Comment by vitaly74** [comment]
thank you very much)
Good weekend ;)

**Comment by liaan** [comment]
can you please start the monitor.py with -d and check the  log/out.log file .. it should say on which line the error occurs

**Comment by vitaly74** [comment]
Hello! thank you for answer

python3 ./monitor.py -d
Starting Monitor...
[Errno -2] Name or service not known
Stopping

cat log/out.log
2021-01-19 19:51:17,545,545 DEBUG    [monitor.py:273] /home/vitaly/soft/ballu/broadlink_ac_mqtt/./monitor.py v1.0.17 is starting up
2021-01-19 19:51:17,545,545 DEBUG    [monitor.py:275] Loglevel set to DEBUG
2021-01-19 19:51:17,564,564 INFO     [monitor.py:322] Starting Monitor...
2021-01-19 19:51:17,565,565 DEBUG    [monitor.py:324] Starting mainloop, responding on only events
2021-01-19 19:51:17,566,566 DEBUG    [AcToMqtt.py:285] Coneccting to MQTT: mqtt with client ID = ac_to_mqtt
2021-01-19 19:51:17,618,618 ERROR    [monitor.py:360] [Errno -2] Name or service not known
2021-01-19 19:51:17,618,618 INFO     [monitor.py:159] Stopping

**Comment by liaan** [comment]
ok, that means is not connecting to your MQTT .


Just check your MQTT hostname in the config file.  Its connecting to host  "MQTT" .. guess your running it on localhost, so just update that, or put the hostname or ip of mqtt machine in there.

**Comment by vitaly74** [comment]
Yes, you right! I don't install MQTT)) after install all will be good..but... run script..and nothing
root@raspberrypi:/home/vitaly/soft/ballu/broadlink_ac_mqtt# python3 ./monitor.py 
root@raspberrypi:/home/vitaly/soft/ballu/broadlink_ac_mqtt# 


I don't know python, and run debug:
python3  -m pdb ./monitor.py -Sd

> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(153)<module>()
-> def receiveSignal(signalNumber, frame):
(Pdb) 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(158)<module>()
-> def stop(signalNumber = 0, frame = 0):
(Pdb) 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(174)<module>()
-> def restart(signalNumber = 0, frame = 0):
(Pdb) 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(177)<module>()
-> def init_signal():
(Pdb) 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(197)<module>()
-> def start():
(Pdb) 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(368)<module>()
-> if __name__ == "__main__":
(Pdb) 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(369)<module>()
-> start()
(Pdb) 
SystemExit
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(369)<module>()
-> start()
(Pdb) 
--Return--
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(369)<module>()->None
-> start()
(Pdb) 
SystemExit
> <string>(1)<module>()->None
(Pdb) 
--Return--
> <string>(1)<module>()->None
(Pdb) 
The program exited via sys.exit(). Exit status: 
> /home/vitaly/soft/ballu/broadlink_ac_mqtt/monitor.py(2)<module>()
-> import sys

Can you answer me -why script exit and where my mistake?(

**Comment by liaan** [comment]
Can you run just python3 ./monitor.py -d and paste the output of ../log/out.log please.

**Comment by vitaly74** [comment]
yes....but no file https://tppr.me/2cIVm ( I don't know why...all depend install, python3 work...Ha work normally..

**Comment by liaan** [comment]
is there no files in the log folder ?

**Comment by liaan** [comment]
closing, not feedback
