### ISSUE TITLE
ambient temperature is 0

### ISSUE THREAD

**Issue by pachol95** [liaan/broadlink_ac_mqtt#66]
I can set temperature, change mode and turn on/off AC but ambient temperature is 0*C. I have noxa AC.

**Comment by wayne-love** [comment]
Seeing the same here, nothing is being returned in the ambient temperature mqtt topic.

**Comment by liaan** [comment]
looking at it.. think its due to debugging other issues

**Comment by liaan** [comment]
Please do pull of latest release (1.1.3) .. should be working again

**Comment by liaan** [comment]
Closing, should be fixed .. will open again if not
