### ISSUE TITLE
Feature Request: HACS compatible version

### ISSUE THREAD

**Issue by tomhaste** [liaan/broadlink_ac_mqtt#72]
Hey! Great bit of code. Im running a Portainer just for it. Would it be possible to have it in a HACS friendly format? 
https://hacs.xyz/docs/publish/python_script

**Comment by liaan** [comment]
Morning

I think someone did a fork of the script already for HACS .. I'll see if I can find it again...

**Comment by lezlikov** [comment]
I also really need such a thing

**Comment by cconde** [comment]
+1

**Comment by balkonrad** [comment]
@liaan any chance to add this? On HA, it is impossible to launch a docker.

**Comment by liaan** [comment]
Hi, 

I will have to check for you guys.  I don't run HA (yet) so have VERY little knowledge of it, especially coding side

I know someone already did port this library to HA converting it to javascript if I recall, I just could not find it quickly now on google.. will do some more digging

L:

**Comment by Zauberio** [comment]
following this topic, I'd love to get my AC integrated
