### ISSUE TITLE
[Errno -2] Name or service not known

### ISSUE THREAD

**Issue by balkonrad** [liaan/broadlink_ac_mqtt#73]
Hi,

I realize that this is probably my mistake(not a software bug), but I am opening a thread asking for help. Steps which I takes:

1. pip install paho-mqtt
2. pip install pyyaml
3. pip install PyCrypto
4. git clone https://github.com/liaan/broadlink_ac_mqtt.git
5. cd broadlink_ac_mqtt
6. cp settings/config_sample.yml settings/config.yml
7. open settings/config.yml with your editor (nano / vi) and add your MQTT details
8. run python monitor.py

```
root@proxmox:~/broadlink_ac_mqtt# ./monitor.py -S
*********** start copy below ************
devices:
- ip: X.x.x.x.
  mac: asddsadsa
  name: ''
  port: 80

*********** stop copy above ************
```

```
root@proxmox:~/broadlink_ac_mqtt# ./monitor.py -Hd
Starting Monitor...
[Errno -2] Name or service not known
Stopping

```

What is missing here?

**Comment by liaan** [comment]
Morning.
Check your MQTT server settings, make sure your device can resolve the mqtt hostname you entered into the config.

From: Konrad Bal ***@***.***>
Sent: Sunday, 06 June 2021 23:42
To: liaan/broadlink_ac_mqtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liaan/broadlink_ac_mqtt] [Errno -2] Name or service not known (#73)


Hi,

I realize that this is probably my mistake and not a software bug, but I am opening a thread asking for help. Steps which I takes:

  1.  pip install paho-mqtt
  2.  pip install pyyaml
  3.  pip install PyCrypto
  4.  git clone https://github.com/liaan/broadlink_ac_mqtt.git<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliaan%2Fbroadlink_ac_mqtt.git&data=04%7C01%7C%7C3646210a724d430dfc6c08d92933db57%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637586124954194039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5ohQAxlTFouNLtzsmjAhc2XUz8FWCaXzDqOkKsO9SHI%3D&reserved=0>
  5.  cd broadlink_ac_mqtt
  6.  cp settings/config_sample.yml settings/config.yml
  7.  open settings/config.yml with your editor (nano / vi) and add your MQTT details
  8.  run python monitor.py

***@***.***:~/broadlink_ac_mqtt# ./monitor.py -S

*********** start copy below ************

devices:

- ip: X.x.x.x.

  mac: asddsadsa

  name: ''

  port: 80



*********** stop copy above ************

***@***.***:~/broadlink_ac_mqtt# ./monitor.py -Hd

Starting Monitor...

[Errno -2] Name or service not known

Stopping



What is missing here?

-

**Comment by tgrosz** [comment]
Hi, sorry for asking here - but where can I ask for help? I have an RCool Display 2 unit, it works with AC Freedom - but the script can not find it,

**Comment by liaan** [comment]
Open a new issue is simplest, then can normally discuss on discord if its big issue
