### ISSUE TITLE
Cannot connect to AC unit

### ISSUE THREAD

**Issue by tgrosz** [liaan/broadlink_ac_mqtt#74]
Hi,
I have an RCool Display 2 unit. It works with AC Freedom.
I tried to run the script on a Raspberry Pi with Hassio, on WSL (here I guess the networking won't be good, as I cannot put WSL to the same subnet as the unit) and the docker version on my Windows laptop.
In docker after modifying the config I get
```
ac2mqtt | Starting Monitor...
ac2mqtt | something went wrong, no devices found
```
from terminal running with -S option the script says
No devices found, make sure you are on same network broadcast segment as device/s

with -s
Starting Monitor...
[Errno -2] Name does not resolve
Stopping

I have no idea how to continue.

**Comment by liaan** [comment]
the name does not resolve part is due to mqtt server setting in your config file, make sure that its correct and you can ping that name

you must be on same subnet to discover.  it does a broadcast on 255.255.255.255 to find devices.  So peer communication on wifi must be enabled and on same ip subnet.

**Comment by tgrosz** [comment]
mqtt is fixed (forgot to save image) - now the error is the same something went wrong
I can ping the unit (192.168.0.42) from docker (192.168.65.15), so if the broadcast is 255... then I guess it's ok
The routing table
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.65.1    0.0.0.0         UG    0      0        0 eth0
127.0.0.0       0.0.0.0         255.0.0.0       U     0      0        0 lo
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-82095bb9179f
192.168.65.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.65.5    0.0.0.0         255.255.255.255 UH    0      0        0 services1

and the default route to the AC unit is via eth0

**Comment by liaan** [comment]
You need to get your AC and Docker on same subnet.  it uses UDP broadcast/multicast on 255.255.255.255.   So the AC will will only be able to respond on 192.168.0.0/24. (assume you have /24 setup)

Actually can't even remember if it uses IP address or just straight MAC to communicate.    You will need to figure out how to get the 2 devices on the same subnet to get it to work .

If you cannot get the -S to dump you the devices, the whole script gonna fail in essence.

**Comment by tgrosz** [comment]
Ok, went back to the PI (hassio + portainer + docker version with host networking)
root@ac2mqtt:/app/ac2mqtt# ./monitor.py -S -dir /config
Authentication Failed to AC
Traceback (most recent call last):
  File "./monitor.py", line 387, in <module>
    start()
  File "./monitor.py", line 319, in start
    discover_and_dump_for_config(config)
  File "./monitor.py", line 35, in discover_and_dump_for_config
    devices = AC.discover()
  File "/app/ac2mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 47, in discover
    discovered_devices = broadlink.discover(timeout=5)
  File "/app/ac2mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 116, in discover
    dev = gendevice(devtype, host, mac,name=name,cloud=cloud)
  File "/app/ac2mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 19, in gendevice
    return ac_db(host=host, mac=mac,name=name, cloud=cloud,devtype= devtype,update_interval = 0)
TypeError: __init__() should return None

**Comment by liaan** [comment]
ok you talking above my pay grade.. .. no clue how nay of those work, i'm to old to learn all these new things ;-)

is the machine you trying to connect from on the 192.168.0.0 subnet?

if you want, we can chat on discord:  https://discord.gg/49V3Uh2u

**Comment by Zauberio** [comment]
check your config file, the Host, its not "mqtt", you have to replace that with the IP of the mqtt server
