### ISSUE TITLE
Cannot communicate with Wifi module - select network interface

### ISSUE THREAD

**Issue by hwcconde** [liaan/broadlink_ac_mqtt#77]
I can command my AC using AC Freedom. It's an AUX with broadlink module.
I can see the mac, ip and port in the details of the application.
I can ping the device from the Raspberry.

Monitor is not able to find it and neither can communicate with it:

pi@HASS:~/broadlink_ac_mqtt $ ./monitor.py
Starting Monitor...
something went wrong, no devices found
Stopping

I believe it may be because I have several network interfaces at once, including WiFi, Ethernet and some virtual interfaces.

How can I specify the monitor which is the proper interface to look into?
Thanks

**Comment by liaan** [comment]
> I can command my AC using AC Freedom. It's an AUX with broadlink module.
> I can see the mac, ip and port in the details of the application.
> I can ping the device from the Raspberry.
> 
> Monitor is not able to find it and neither can communicate with it:
> 
> pi@HASS:~/broadlink_ac_mqtt $ ./monitor.py
> Starting Monitor...
> something went wrong, no devices found
> Stopping
> 
> I believe it may be because I have several network interfaces at once, including WiFi, Ethernet and some virtual interfaces.
> 
> How can I specify the monitor which is the proper interface to look into?
> Thanks

can you do a monitor.py -S  (capital S)

do you get anything?

**Comment by hwcconde** [comment]
No, it just fails to find it.

Currently we have the AP and there is connected the broadlink module, the Raspberry and my mobile.

My mobile can communicate with the AC and the raspberry can ping it, but monitor.py can't discover it.

Raspberry has an additional network interface because Ethernet is connected to a different network (with different addressing) and it also has several virtual interfaces.

I think it may be that the monitor is trying to look in a different interface, i.e. Ethernet. 
I'd like to test to force which interface does it bind to...

**Comment by hwcconde** [comment]
If at this line I write the local IP of the WiFi interface:
https://github.com/liaan/broadlink_ac_mqtt/blob/466d421b1b058812deb3918e12f994511ca58252/broadlink_ac_mqtt/classes/broadlink/ac_db.py#L26

Then now the monitor.py -S discovers it.

I'm not happy with that hardcoded solution, but I don't know python.
Can you please add a configuration entry for the interface name, so that the code knows what to look bind to?

Great job!!!

**Comment by liaan** [comment]
> now

mmmmmmmmm  interesting.....   Gues the broadcast just go out of first interface its finds.. will try do som RTFM

I can add the config option ..   its just supper time now .. will try get done 2morrow .. I you dont' year from me, just bump this issue, I will get email alert.

**Comment by hwcconde** [comment]
Can you please review it?

I'm trying to get it working in docker and as the docker compose pulls the latest git I cannot point it what is the interface to bind to...

**Comment by liaan** [comment]
> Can you please review it?
> 
> I'm trying to get it working in docker and as the docker compose pulls the latest git I cannot point it what is the interface to bind to...

Sorry, I got stuck with work .. .  I pushed a new branch:   https://github.com/liaan/broadlink_ac_mqtt/tree/feature/test_bind_ip

you will see in config_sample.yml there is a option "bind_to_ip"  .. can you try that and see if discovery works?

**Comment by hwcconde** [comment]
I'm not able to see that option in the sample config...

**Comment by hwcconde** [comment]
I guessed it was part of the service and I can confirm it's working properly

Great job!
