### ISSUE TITLE
Feature Request: Control of the Vertical and or Horizontal "Fixation"

### ISSUE THREAD

**Issue by LordDethman** [liaan/broadlink_ac_mqtt#84]
Is there any chance of adding control of the vertical / horizontal articulation? My units can only do the vertical and if I turn the unit off with broadlink_ac_mqtt, when I turn it back on the "fixation" is off. I have to use the hand remote to turn it back on.

Also my unit does also have an "Auto" Heating / Cooling mode. Any chance of getting that option?

**Comment by liaan** [comment]
hi

The script can already do it via the mqtt  commands fixation_v or fixation_h with values as per below..   If you want to have it in HA, I can try and add it, just dont' have HA installed anywhere so will be a while.

```
class FIXATION:
                        class VERTICAL:
                                #STOP= 0b00000000
                                TOP= 0b00000001
                                MIDDLE1= 0b00000010
                                MIDDLE2 = 0b00000011
                                MIDDLE3 = 0b00000100
                                BOTTOM= 0b00000101
                                SWING= 0b00000110
                                AUTO = 0b00000111

                        class HORIZONTAL:               ##Don't think this really works for all devices.
                                LEFT_FIX = 2
                                LEFT_FLAP = 1
                                LEFT_RIGHT_FIX = 7
                                LEFT_RIGHT_FLAP = 0
                                RIGHT_FIX = 6
                                RIGHT_FLAP = 5
                                ON = 0
                                OFF = 1
```

**Comment by LordDethman** [comment]
Nice, OK I will give it a try. 

 If I understand correctly I would need to add this to the device array in the ASToMqtt.py file `,"fixation_v":["swing","auto","stop"]` ?

And would I need to uncomment the `#STOP= 0b00000000` in the ac_db.py?

If you dont have time I can play with it myself. Not like I cant change it back myself if I mess it up.

Thanks for giving the time, I know you are a busy person.

**Comment by liaan** [comment]
> Nice, OK I will give it a try.
> 
> If I understand correctly I would need to add this to the device array in the ASToMqtt.py file `,"fixation_v":["swing","auto","stop"]` ?
> 
> And would I need to uncomment the `#STOP= 0b00000000` in the ac_db.py?
> 
> If you dont have time I can play with it myself. Not like I cant change it back myself if I mess it up.
> 
> Thanks for giving the time, I know you are a busy person.

umm... not sure about the comment out of the STOP , but you can try

my testing using the AC freedom app years ago was it was either auto, or one of the other positions.. one could not stop it randomly .. might have changed

I would guess in your case Auto might be better option than stop.

**Comment by LordDethman** [comment]
10/4 So I will give it a try. 
Does `,"fixation_v",["auto","swing"]` seem right for the device array? Sorry Python is not my strong suit. I can pluck my way through it but a bit slow. I am much more confident with a few proprietary control programming languages lol.

**Comment by LordDethman** [comment]
ok I got it to read the `fixation_v` without any real issues. The payload was different on my unit for the "swing" setting but I was able to fix that in the classes. But I seem to be missing something to be able to command it. 

Do i need to create a `def set_fixation_v` somewhere? I see a `def set_` for just about everything expect for fixation.

**Comment by liaan** [comment]
> 10/4 So I will give it a try.
> Does `,"fixation_v",["auto","swing"]` seem right for the device array? Sorry Python is not my strong suit. I can pluck my way through it but a bit slow. I am much more confident with a few proprietary control programming languages lol.

haha... i hate python, with a passion.   
Basicly it monitors the mqtt for new messages.  then check the topic when new message arrives, This will be the  "function".   The value of the topic will what todo with the "function" (command)

So if you look in actomqtt.py .. line ~300 .. it checkes what is received on the mqtt "function" and very lazy "if" tree to go through the options.

So you will need to do somethign like'
```
if function ==  "fixation_v":	
			try:
				if self.device_objects.get(address):
					status = self.device_objects[address].set_fixationv(value)
					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return

```

And then in ac_db.py add set_fixation_v

```
def set_fixationv(self,fixation_text):
		##Make sure latest info as cannot just update one things, have set all
		self.get_ac_states()
		
		fixation = self.STATIC.FIXATION.VERTICAL.__dict__.get(fixation_text.upper())
		if fixation != None:
			self.status['fixation_v'] = mode
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug("Not found mode value %s" , str(mode_text))
			return False
```


not sure if you noticed you can run monitor.py -d  and will write huge amount of debugging info

so if you want to see the changes that you make using your remote, that might help as well, just check the values comming through there  or subscribe to the mqtt topic

hope that gives you some direction 

If you get it to work , do a pull request .. or dump the code here, so can maybe add it for other ?

**Comment by LordDethman** [comment]
> > 10/4 So I will give it a try.
> > Does `,"fixation_v",["auto","swing"]` seem right for the device array? Sorry Python is not my strong suit. I can pluck my way through it but a bit slow. I am much more confident with a few proprietary control programming languages lol.
> 
> haha... i hate python, with a passion.
> Basicly it monitors the mqtt for new messages. then check the topic when new message arrives, This will be the "function". The value of the topic will what todo with the "function" (command)
> 
> So if you look in actomqtt.py .. line ~300 .. it checkes what is received on the mqtt "function" and very lazy "if" tree to go through the options.
> 
> So you will need to do somethign like'
> 
> ```
> if function ==  "fixation_v":	
> 			try:
> 				if self.device_objects.get(address):
> 					status = self.device_objects[address].set_fixationv(value)
> 					
> 					if status :
> 						self.publish_mqtt_info(status)
> 				else:
> 					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
> 					return
> 			except Exception as e:	
> 				logger.critical(e)
> 				return
> ```
> 
> And then in ac_db.py add set_fixation_v
> 
> ```
> def set_fixationv(self,fixation_text):
> 		##Make sure latest info as cannot just update one things, have set all
> 		self.get_ac_states()
> 		
> 		fixation = self.STATIC.FIXATION.VERTICAL.__dict__.get(fixation_text.upper())
> 		if fixation != None:
> 			self.status['fixation_v'] = mode
> 			self.set_ac_status()
> 			return self.make_nice_status(self.status)
> 		else:
> 			self.logger.debug("Not found mode value %s" , str(mode_text))
> 			return False
> ```
> 
> not sure if you noticed you can run monitor.py -d and will write huge amount of debugging info
> 
> so if you want to see the changes that you make using your remote, that might help as well, just check the values comming through there or subscribe to the mqtt topic
> 
> hope that gives you some direction
> 
> If you get it to work , do a pull request .. or dump the code here, so can maybe add it for other ?

Thank you, I will see if I can make this work for me.

**Comment by fmobile999** [comment]
Hi! What about vertical / horizontal fixation use? Is this code working?

**Comment by andremain** [comment]
I really need this to be able to use this integration. Too bad the guy didn't even comment if he made it or not.

**Comment by liaan** [comment]
> I really need this to be able to use this integration. Too bad the guy didn't even comment if he made it or not.

Why you not just copy paste the code above and see if it works?

**Comment by andremain** [comment]
> > I really need this to be able to use this integration. Too bad the guy didn't even comment if he made it or not.
> 
> Why you not just copy paste the code above and see if it works?

I saw this at 2 in the morning. I am planning to do so when i get to work

**Comment by andremain** [comment]
OK @liaan , can i have some help with trying to do this as i am not a programmer?

So First things first this is my edit to the AcToMqtt.py File

I made a fork of your GitHub page. Please check my indentations. I have added the class at line 26 and the function at line 472.

https://github.com/andremain/broadlink_ac_mqtt/blob/master/AcToMqtt.py%20with%20V%20Swing%20(Fixation)

When i try to run monitor.py it gives me an error:

`  File "/home/pi/broadlink_ac_mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 487
    return
SyntaxError: 'return' outside function`

I don't understand why this is outside the function or where it should be. 

Also here is the second piece of code:

https://github.com/andremain/broadlink_ac_mqtt/blob/master/ac_db.py%20with%20V%20Swing%20(Fixation)

The extra piece of code is at line 26

I also made a guide to help out others https://community.home-assistant.io/t/broadlink-ac-integration-aux-dunham-rcool-akai-rinnai-kenwood-tornado-ballu/342789

Can you please help me?

**Comment by LordDethman** [comment]
Yeah I have not had a chance to update and test this one. I have been very busy at work. If I have a weekend without a kids birthday party or a wedding I will try and test this on my setup.

**Comment by liaan** [comment]
sorry, also swamped..   its crazy session at "work" so not even had change to read anything on here

as soos as things are bit quiter will have looksee.

**Comment by andremain** [comment]
Thank you very much guys! Appreciate it! Both of you. If you can get the swing working for me then it is GO otherwise it's a deal breaker. And trust me this is a lot better than making IR command batches for the AC units.

**Comment by liaan** [comment]
This was my first "major" "script" in Python ..   I had todo ALOT of reading and hours of debugging and .. If I could figure python out, sure you can 2 ;-)

I tried to comment the script as much as possible.. so it should make half sense.    

if you have questions.. I can easily asnwer when having brake, its just difficult to sit down and spin up my python development setup to get this tested.   I don't do any python coding except for this script, so its always mission to get things going to do any new dev.

**Comment by andremain** [comment]
i am really useless when it comes to coding. I have been struggling with this for 3 days and no go...

**Comment by liaan** [comment]
haha.. put the code in.. start monitor.py -d  and check the logs

Does it start, or do you get errors?

if starts .. what command do you sent to mqtt to test the verticals?

**Comment by andremain** [comment]
Apologies, I did not see your comment Liaan.

I have already tried. Here is the error i get:

When i try to run monitor.py it gives me an error:

File "/home/pi/broadlink_ac_mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 487 return SyntaxError: 'return' outside function

I don't understand why this is outside the function or where it should be.

Here are both the modified files i made. What do you think?

https://github.com/andremain/broadlink_ac_mqtt/blob/master/ac_db.py%20with%20V%20Swing%20(Fixation)

The extra piece of code is at line 26

I also made a guide to help out others https://community.home-assistant.io/t/broadlink-ac-integration-aux-dunham-rcool-akai-rinnai-kenwood-tornado-ballu/342789

**Comment by liaan** [comment]
ok, feeling guilty.. busy seting up dev enviroment, will try get this sorted today

**Comment by liaan** [comment]
> 
> 
> Is there any chance of adding control of the vertical / horizontal articulation? My units can only do the vertical and if I turn the unit off with broadlink_ac_mqtt, when I turn it back on the "fixation" is off. I have to use the hand remote to turn it back on.
> 
> Also my unit does also have an "Auto" Heating / Cooling mode. Any chance of getting that option?

The auto mode for heating cooling is Mqtt command MODE: AUTO   .. so just send that in MQTT
 mosquitto_pub -h mqtt.internall  -t '/aircon/mac_address/mode/set' -m 'AUTO'
class MODE:
			COOLING	=	0b00000001
			DRY		=	0b00000010
			HEATING	=	0b00000100
			AUTO	=	0b00000000
			FAN 	=	0b00000110   

Added the verticals / horizontal
mqtt command:
Horizontal
 mosquitto_pub -h mqtt.internall  -t '/aircon/mac_address/fixation_h/set' -m 'RIGHT'
Veritcal
 mosquitto_pub -h mqtt.internall  -t '/aircon/mac_address/fixation_v/set' -m 'SWING'

Here list of options for vertical and horizontal commands
```
class VERTICAL:
				 
				TOP= 0b00000001
				MIDDLE1= 0b00000010
				MIDDLE2 = 0b00000011
				MIDDLE3 = 0b00000100
				BOTTOM= 0b00000101
				SWING= 0b00000110
				AUTO = 0b00000111

class HORIZONTAL:		##Don't think this really works for all devices. .. Mine only support ON OFF
				LEFT_FIX = 2
				LEFT_FLAP = 1
				LEFT_RIGHT_FIX = 7
				LEFT_RIGHT_FLAP = 0
				RIGHT_FIX = 6
				RIGHT_FLAP = 5
				ON = 0
				OFF = 1

**Comment by liaan** [comment]
If you need this in HA .. then please send me the HA mqtt autoconfig setup so I can add it.

**Comment by andremain** [comment]
> If you need this in HA .. then please send me the HA mqtt autoconfig setup so I can add it.

Thank you so much @liaan. Do i need to reinstall the program on my linux server?

I am sorry i am not sure what you mean by mqtt autonfig. 

is it this thing?

logins: []
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false

Or this: ?

climate:
- action_topic: /aircon/c8f742348bec/homeassistant/set
  availability_topic: /aircon/LWT
  current_temperature_topic: /aircon/c8f742348bec/ambient_temp/value
  fan_mode_command_topic: /aircon/c8f742348bec/fanspeed_homeassistant/set
  fan_mode_state_topic: /aircon/c8f742348bec/fanspeed_homeassistant/value
  fan_modes:
  - Auto
  - Low
  - Medium
  - High
  - Turbo
  - Mute
  max_temp: 32.0
  min_temp: 16.0
  mode_command_topic: /aircon/c8f742348bec/mode_homeassistant/set
  mode_state_topic: /aircon/c8f742348bec/mode_homeassistant/value
  modes:
  - 'off'
  - cool
  - heat
  - fan_only
  - dry
  name: 'Living Room AC'
  platform: mqtt
  precision: 0.5
  temp_step: 0.5
  temperature_command_topic: /aircon/c8f742348bec/temp/set
  temperature_state_topic: /aircon/c8f742348bec/temp/value
  unique_id: c8f742348bec
  swing_mode_command_topic: /aircon/c8f742348bec/fixation_v/set
  swing_mode_state_topic: /aircon/c8f742348bec/fixation_v/value
  swing_modes:
  - AUTO
  - 0

**Comment by andremain** [comment]
> class VERTICAL:
> 				 
> 				TOP= 0b00000001
> 				MIDDLE1= 0b00000010
> 				MIDDLE2 = 0b00000011
> 				MIDDLE3 = 0b00000100
> 				BOTTOM= 0b00000101
> 				SWING= 0b00000110
> 				AUTO = 0b00000111
> 
> class HORIZONTAL:		##Don't think this really works for all devices. .. Mine only support ON OFF
> 				LEFT_FIX = 2
> 				LEFT_FLAP = 1
> 				LEFT_RIGHT_FIX = 7
> 				LEFT_RIGHT_FLAP = 0
> 				RIGHT_FIX = 6
> 				RIGHT_FLAP = 5
> 				ON = 0
> 				OFF = 1

Where do i need to add this?

**Comment by liaan** [comment]
> > class VERTICAL:
> > ```
> >   		TOP= 0b00000001
> >   		MIDDLE1= 0b00000010
> >   		MIDDLE2 = 0b00000011
> >   		MIDDLE3 = 0b00000100
> >   		BOTTOM= 0b00000101
> >   		SWING= 0b00000110
> >   		AUTO = 0b00000111
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > class HORIZONTAL:		##Don't think this really works for all devices. .. Mine only support ON OFF
> > LEFT_FIX = 2
> > LEFT_FLAP = 1
> > LEFT_RIGHT_FIX = 7
> > LEFT_RIGHT_FLAP = 0
> > RIGHT_FIX = 6
> > RIGHT_FLAP = 5
> > ON = 0
> > OFF = 1
> 
> Where do i need to add this?

Hi, 

Nowhere .. those are the support values for the mqtt command to set the fixations.

IE: mosquitto_pub -h mqtt.internall -t '/aircon/mac_address/fixation_h/set' -m '**RIGHT**'

**Comment by andremain** [comment]
> Nowhere .. those are the support values for the mqtt command to set the fixations.
> 
> IE: mosquitto_pub -h mqtt.internall -t '/aircon/mac_address/fixation_h/set' -m '**RIGHT**'

Don't i need to do any changes to the broadlink_ac_mqtt program i donwloaded to my linux machine?

**Comment by andremain** [comment]
It works! A million thanks @liaan !!! Just remove the old code and redownload the new one. Setup the config file again and paste this to your configuration.yaml file in home assistant changing the mac address

```
climate:
- action_topic: /aircon/c8f742348bec/homeassistant/set
  availability_topic: /aircon/LWT
  current_temperature_topic: /aircon/c8f742348bec/ambient_temp/value
  fan_mode_command_topic: /aircon/c8f742348bec/fanspeed_homeassistant/set
  fan_mode_state_topic: /aircon/c8f742348bec/fanspeed_homeassistant/value
  fan_modes:
  - Auto
  - Low
  - Medium
  - High
  - Turbo
  - Mute
  max_temp: 32.0
  min_temp: 16.0
  mode_command_topic: /aircon/c8f742348bec/mode_homeassistant/set
  mode_state_topic: /aircon/c8f742348bec/mode_homeassistant/value
  modes:
  - 'off'
  - cool
  - heat
  - fan_only
  - dry
  name: 'Living Room AC'
  platform: mqtt
  precision: 0.5
  temp_step: 0.5
  temperature_command_topic: /aircon/c8f742348bec/temp/set
  temperature_state_topic: /aircon/c8f742348bec/temp/value
  unique_id: c8f742348bec
  swing_mode_command_topic: /aircon/c8f742348bec/fixation_v/set
  swing_mode_state_topic: /aircon/c8f742348bec/fixation_v/value
  swing_modes:
  - SWING
  - TOP
  - AUTO
  - MIDDLE1
  - MIDDLE2
  - MIDDLE3
```

**Comment by andremain** [comment]
Is there any way to set the swing & Fan Speed in HA automations? I can only set the HVAC modes.

**Comment by yoedf** [comment]
Hi @liaan, i created PR to add this to the auto discovery by HA (tested with my HA)
https://github.com/liaan/broadlink_ac_mqtt/pull/92

**Comment by liaan** [comment]
Thanks
Will have to check the other merge request for same function as well .. just have not had time to spend don the project lately..  hopefully will have gap next week

**Comment by yoedf** [comment]
Hi @liaan do you think you will be able to merge my PR soon (https://github.com/liaan/broadlink_ac_mqtt/pull/92)?

**Comment by yoed-fried-deel** [comment]
Hi @liaan, any estimation when you will be able to merge this change?

**Comment by liaan** [comment]
appologies, i've not looked at github in months, never saw emails, weird

its merged now. will do build as well

**Comment by andremain** [comment]
Hi Liaan. Thank you btw i have been using it for quite some time now and it works well! Even the fixation part you added.
Is there a way we can add this to HACS directly to HA? The only issue i have is that it keeps loosing the connection and i have to restart it.

**Comment by liaan** [comment]
> Hi Liaan. Thank you btw i have been using it for quite some time now and it works well! Even the fixation part you added. Is there a way we can add this to HACS directly to HA? The only issue i have is that it keeps loosing the connection and i have to restart it.

Someone did port the code to  plugin for HA (well, few years ago, not sure if maintained still)

Which part you need to restart?  cause it should not "loose" connection as the mqtt should reconnect whole time.

only other thing is maybe reduce the poll interval to the AC?  sometimes the AC's cannot handle to many queries.

**Comment by andremain** [comment]
Really do you remember the name of the integration by any chance?

The service does not stop but sometimes when i restart HA or update it i have to manually stop and restart the service.

**Comment by liaan** [comment]
> Really do you remember the name of the integration by any chance?
> 
> The service does not stop but sometimes when i restart HA or update it i have to manually stop and restart the service.

there setting for persistance or someting for HA that should fix that.. let me try find config, been to long

**Comment by liaan** [comment]
auto_discovery_topic_retain: False

if that is False, set it to True, should fix the HA remembering device

**Comment by andremain** [comment]
is this meant for inside HA or the broadlink ac mqtt?

**Comment by liaan** [comment]
> is this meant for inside HA or the broadlink ac mqtt?

its in the config file, where you set the mqtt server etc. 

```
mqtt:
    host: mqtt
    port: 1883
    client_id: ac_to_mqtt
    user: koos
    passwd: koos_se_password
    topic_prefix: /aircon
    auto_discovery_topic: homeassistant
    auto_discovery_topic_retain: true
    discovery: False
````

**Comment by andremain** [comment]
Ok thank you. It was set to:    auto_discovery_topic_retain:  False. I assume the True should be a capital T?

**Comment by liaan** [comment]
> Ok thank you. It was set to: auto_discovery_topic_retain: False. I assume the True should be a capital T?

actually, I don't think it matters..   you can try it 

what it does it makes the MQTT topic message as persistant, so each time the HA reconnect to the MQTT it gets the HA config message again and again

**Comment by advokatden** [comment]
Good afternoon!I get the following error when I turn on SWING mode:

Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:628
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 16:54:33 (26 occurrences)
Last logged: 16:59:00

Invalid swing_modes mode: 0


Data from mqtt explorer:

![Снимок экрана 2022-06-12 в 17 11 29](https://user-images.githubusercontent.com/73667341/173237365-6691535a-882f-4491-aa4c-f74ab2edbdca.png)

**Comment by advokatden** [comment]
> Добрый день!Я получаю следующую ошибку, когда включаю режим КАЧАНИЯ:
> 
> Регистратор: homeassistant.components.mqtt.climate Источник: components/mqtt/climate.py: 628 Интеграция: MQTT ([документация](https://www.home-assistant.io/integrations/mqtt), [проблемы](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22)) Первое появление: 16:54:33 (26 случаев) Последнее появление: 16:59:00
> 
> Недопустимый режим swing_modes: 0
> 
> Данные из mqtt explorer:
> 
> ![Снимок экрана 2022-06-12 в 17 11 29](https://user-images.githubusercontent.com/73667341/173237365-6691535a-882f-4491-aa4c-f74ab2edbdca.png)

Fixed the config ac_db.py . It helped

**Comment by liaan** [comment]
hi

Sorry, but I don't have HA installed anywhere at moment, so cannot test any integrations.....

You say you got it fixed, what did you change so I can update code?

**Comment by advokatden** [comment]
> # 92

good day!

Fixed SWING mode = 0
	

class STATIC:
		##Static stuff
		class FIXATION:
			class VERTICAL:
				#STOP= 0b00000000
				TOP= 0b00000001
				MIDDLE1= 0b00000010
				MIDDLE2 = 0b00000011
				MIDDLE3 = 0b00000100
				BOTTOM= 0b00000101
				#SWING= 0b00000110
                                 **SWING = 0**
				AUTO = 0b00000111

**Comment by advokatden** [comment]
> привет
> 
> Извините, но на данный момент у меня нигде не установлен HA, поэтому я не могу протестировать какие-либо интеграции.....
> 
> Вы говорите, что исправили это, что вы изменили, чтобы я мог обновить код?

I wanted to say a big thank you for your work!!

**Comment by liaan** [comment]
> > # 92
> 
> good day!
> 
> Fixed SWING mode = 0
> 
> class STATIC: ##Static stuff class FIXATION: class VERTICAL: #STOP= 0b00000000 TOP= 0b00000001 MIDDLE1= 0b00000010 MIDDLE2 = 0b00000011 MIDDLE3 = 0b00000100 BOTTOM= 0b00000101 #SWING= 0b00000110 **SWING = 0** AUTO = 0b00000111

thanks..  w
