### ISSUE TITLE
Temperature reading resets to 1 after reaching 31degrees

### ISSUE THREAD

**Issue by sgtaziz** [liaan/broadlink_ac_mqtt#87]
First off, let me just say, this is an amazing project. Very well done, it's much appreciated!

I found an issue where if ambient temperatures reach 32 degrees, it resets to 1. For example, 32 = 1, 33 = 2, 34 = 3, etc. From messing around, I was able to fix this issue by adjusting the `ambient_temp` calculation in ac_db.py as below:
```
ambient_temp = (response_payload[15] - 0b00100000) + (float(response_payload[31]) / 10)
```
This is slightly different than the original, which was instead ignoring any bits over 5. The second part is only for the decimal points.

**Comment by fmobile999** [comment]
Thanks. Ballu bsui-18hn8, you code working fine. Maybe, you can put this in pull request?

**Comment by liaan** [comment]
Hi, 

Thanks .. I just wrote it for myself, and somehow got rather big traction And my apologies for not seeing the issue..  no idea how missed it (well, actually I do know, hardly ever on github anymore).

My aircon only goes to 32 .. that why all coded to 32 ;-)  

Probably can update this, but now we getting into problem with which AC's going to break etc.. Might have to add to config file with different library..

There is also check in the main script to limit the temp to 32, so any value above 32 will be reset to 32.
