### ISSUE TITLE
Error in ac_db.py

### ISSUE THREAD

**Issue by fmobile999** [liaan/broadlink_ac_mqtt#90]
Hi, Liaan!
At row 711 in ac_db.py instead:
`status_nice['fixation_h'] = self.get_key(self.STATIC.FIXATION.VERTICAL.__dict__,status['fixation_h'])`
must be:
`status_nice['fixation_h'] = self.get_key(self.STATIC.FIXATION.HORIZONTAL.__dict__,status['fixation_h'])`

Great thanks for you job!

**Comment by fmobile999** [comment]
And at row 860 instead:
`self.status['fixation_h'] = response_payload[10]  & 0b00000111`
must be:
`self.status['fixation_h']  = response_payload[11] >> 5 & 0b00000111`

Great thanks again!!

**Comment by liaan** [comment]
Interesting..  this was working on our aircons ( I thought).  Will check it out

thanks

**Comment by liaan** [comment]
Sigh.. to much copy pasting
Thanks


From: Sergey ***@***.***>
Sent: Friday, 14 January 2022 22:45
To: liaan/broadlink_ac_mqtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liaan/broadlink_ac_mqtt] Error in ac_db.py (Issue #90)


Hi, Liaan!
At row 711 in ac_db.py instead:
status_nice['fixation_h'] = self.get_key(self.STATIC.FIXATION.VERTICAL.__dict__,status['fixation_h'])
must be:
status_nice['fixation_h'] = self.get_key(self.STATIC.FIXATION.HORIZONTAL.__dict__,status['fixation_h'])

Great thanks for you job!

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliaan%2Fbroadlink_ac_mqtt%2Fissues%2F90&data=04%7C01%7C%7C4b5ad1b88a734e6fe6a508d9d79ebd11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637777899050405900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4NnhNQusU0sq%2FKSrdQfHnRSxPknPsKLp58QQvDW8gFQ%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAGTCX6U2FYU4KXCSI3ZDBDUWCDM3ANCNFSM5L7XDH6A&data=04%7C01%7C%7C4b5ad1b88a734e6fe6a508d9d79ebd11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637777899050405900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3hJjRyWliy54z7pmFWfrFYs%2FYnZnRhxW5%2FjXS11FN0Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4b5ad1b88a734e6fe6a508d9d79ebd11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637777899050405900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=euil3qPRgyyZPkruDNt7Mf7kV9nCPj%2BuMdWmEAAYfjs%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4b5ad1b88a734e6fe6a508d9d79ebd11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637777899050405900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q%2BdrnC20mudc6TBz56kt519mFvomGxwyVHiUy6XThwA%3D&reserved=0>.

**Comment by fmobile999** [comment]
> this was working on our aircons

Working, but show status of vertical intead horizontal. But horizontal fixation is byte [11].
`895		payload[10] = 0b00000000 | temperature << 3 | self.status['fixation_v'] `
`896		payload[11] = 0b00000000 | self.status['fixation_h'] <<5`

**Comment by fmobile999** [comment]
By copypaste of you code i wrote functions for display, clean, mildew, health and sleep. They work on Ballu BSUI-18HN8, except health - this model has no ionizer.
ac_db.py:
```
        def set_display(self,value):
		##Make sure latest info as cannot just update one things, have set all
		self.get_ac_states()
		
		mode = self.STATIC.ONOFF.__dict__.get(value)
		if mode != None:
			self.status['display'] = mode
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug("Not found display value %s" , str(value))
			return False

	def set_mildew(self,value):
		##Make sure latest info as cannot just update one things, have set all
		self.get_ac_states()
		
		mode = self.STATIC.ONOFF.__dict__.get(value)
		if mode != None:
			self.status['mildew'] = mode
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug("Not found display value %s" , str(value))
			return False

	def set_clean(self,value):
		##Make sure latest info as cannot just update one things, have set all
		self.get_ac_states()
		
		mode = self.STATIC.ONOFF.__dict__.get(value)
		if mode != None:
			self.status['clean'] = mode
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug("Not found display value %s" , str(value))
			return False

	def set_health(self,value):
		##Make sure latest info as cannot just update one things, have set all
		self.get_ac_states()
		
		mode = self.STATIC.ONOFF.__dict__.get(value)
		if mode != None:
			self.status['health'] = mode
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug("Not found display value %s" , str(value))
			return False

	def set_sleep(self,value):
		##Make sure latest info as cannot just update one things, have set all
		self.get_ac_states()
		
		mode = self.STATIC.ONOFF.__dict__.get(value)
		if mode != None:
			self.status['sleep'] = mode
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug("Not found display value %s" , str(value))
			return False
```
AcToMqtt.py:
```
		elif function ==  "display":	
			try:
				if self.device_objects.get(address):					
					status = self.device_objects[address].set_display(value)					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return
		elif function ==  "mildew":	
			try:
				if self.device_objects.get(address):					
					status = self.device_objects[address].set_mildew(value)					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return
		elif function ==  "clean":	
			try:
				if self.device_objects.get(address):					
					status = self.device_objects[address].set_clean(value)					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return
		elif function ==  "health":	
			try:
				if self.device_objects.get(address):					
					status = self.device_objects[address].set_health(value)					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return
		elif function ==  "sleep":	
			try:
				if self.device_objects.get(address):					
					status = self.device_objects[address].set_sleep(value)					
					if status :
						self.publish_mqtt_info(status)
				else:
					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
					return
			except Exception as e:	
				logger.critical(e)
				return
```
maybe it will be useful  for you.

**Comment by liaan** [comment]
Anyhow you can put this in pull request?

**Comment by fmobile999** [comment]
Done

**Comment by advokatden** [comment]
> elif function ==  "display":	
> 			try:
> 				if self.device_objects.get(address):					
> 					status = self.device_objects[address].set_display(value)					
> 					if status :
> 						self.publish_mqtt_info(status)
> 				else:
> 					logger.debug("Device not on list of devices %s, type:%s" % (address,type(address)))
> 					return
> 			except Exception as e:	
> 				logger.critical(e)
> 				return

Good afternoon! Tell me , how do I add control of these modes from HOME ASSISTANT ?
