### ISSUE TITLE
Error starting after shutdown

### ISSUE THREAD

**Issue by winczead** [liaan/broadlink_ac_mqtt#93]
Hi Guys!

It would be an interesting problem...
I set everything, it connects to the climates, I can control all the functions, it starts without a problem if I restart HomeAssistant. Apparently everything is good.
But if I shut down the system and start it later, I get an error message like this when I run monitor.py:

> Traceback (most recent call last):
>   File "/config/custom_components/broadlink_ac_mqtt/monitor.py", line 9, in <module>
>     import broadlink_ac_mqtt.AcToMqtt as AcToMqtt
>   File "/config/custom_components/broadlink_ac_mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 8, in <module>
>     import paho.mqtt.client as mqtt
> ModuleNotFoundError: No module named 'paho'

HA was originally running on an Intel NUC, but now I'm testing it on Hyper-V and it produces the same bug.

Thanks for help!

**Comment by liaan** [comment]
This is python include path issue somehow
Either that or you have multiple version of python running and auto start and manual start use 2 different versions....



From: Vincze Ádám ***@***.***>
Sent: Thursday, 27 January 2022 15:37
To: liaan/broadlink_ac_mqtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liaan/broadlink_ac_mqtt] Error starting after shutdown (Issue #93)


Hi Guys!

It would be an interesting problem...
I set everything, it connects to the climates, I can control all the functions, it starts without a problem if I restart HomeAssistant. Apparently everything is good.
But if I shut down the system and start it later, I get an error message like this when I run monitor.py:

Traceback (most recent call last):
File "/config/custom_components/broadlink_ac_mqtt/monitor.py", line 9, in
import broadlink_ac_mqtt.AcToMqtt as AcToMqtt
File "/config/custom_components/broadlink_ac_mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 8, in
import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'

HA was originally running on an Intel NUC, but now I'm testing it on Hyper-V and it produces the same bug.

Thanks for help!

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliaan%2Fbroadlink_ac_mqtt%2Fissues%2F93&data=04%7C01%7C%7Cb42bfbec6a544c8969dc08d9e19a0ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788874065816999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZLN1yo8lTOfFcf5wSobzA3kKg5LSfnGWen%2FQb0FqYWU%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAGTCXYX3DOXMNY24ILRJZLUYFC6XANCNFSM5M55LS7A&data=04%7C01%7C%7Cb42bfbec6a544c8969dc08d9e19a0ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788874065816999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q9ey4gHSPPEWr0%2Fnn5ILidWYTm0wiXVirtIXvG4YY9k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb42bfbec6a544c8969dc08d9e19a0ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788874065816999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0w%2BljzcuGy9bBMMPivT91De0q88J2B83q9Bk7df04%2BQ%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb42bfbec6a544c8969dc08d9e19a0ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788874065816999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qbfTNBv8ajMTvT4EDuikKQqnxjXEqD72csWP40kdnKc%3D&reserved=0>.
