### ISSUE TITLE
turn on command by default enables Heat mode

### ISSUE THREAD

**Issue by irzayev** [liaan/broadlink_ac_mqtt#98]
good day,
turn on command by default enables Heat mode

How can I change it to this logic:
Turn on enables last mode OR Turn on enables Cooling mode ?

**Comment by liaan** [comment]
Hi

As far I recall it pulls the last status from the aircon and uses that, so there is no "default".  It simply sets the on bit when you press on, rest is what ever was used last.  Sometimes if you use remotes, it goes into different state.

Can you not setup your HA to set AC to correct mode with script or temp?  sorry, I have no knowledge of HA.


From: irzayev ***@***.***>
Sent: Wednesday, 22 June 2022 07:44
To: liaan/broadlink_ac_mqtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liaan/broadlink_ac_mqtt] turn on command by default enables Heat mode (Issue #98)


good day,
turn on command by default enables Heat mode

How can I change it to this logic:
Turn on enables last mode OR Turn on enables Cooling mode ?

-

**Comment by liaan** [comment]
Checked code

you can use some of below as commands , it will turn aircon on, with mode set
```
	def set_homekit_mode(self,status):
		if type(status) is not str:
			self.logger.debug('Status variable is not string %s',type(status))
			return False
		
		if status.lower() == 'coolon':
			self.status['mode'] = self.STATIC.MODE.COOLING
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)
		elif status.lower() == 'heaton':
			self.status['mode'] = self.STATIC.MODE.HEATING
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)

```

**Comment by irzayev** [comment]
> Checked code
> 
> you can use some of below as commands , it will turn aircon on, with mode set
> 
> ```
> 	def set_homekit_mode(self,status):
> 		if type(status) is not str:
> 			self.logger.debug('Status variable is not string %s',type(status))
> 			return False
> 		
> 		if status.lower() == 'coolon':
> 			self.status['mode'] = self.STATIC.MODE.COOLING
> 			self.status['power'] =  self.STATIC.ONOFF.ON
> 			self.set_ac_status()
> 			return self.make_nice_status(self.status)
> 		elif status.lower() == 'heaton':
> 			self.status['mode'] = self.STATIC.MODE.HEATING
> 			self.status['power'] =  self.STATIC.ONOFF.ON
> 			self.set_ac_status()
> 			return self.make_nice_status(self.status)
> ```

Thank you! I'm not good in coding, could you tell me where should I add it or change it? which file and lines?
Thx

**Comment by liaan** [comment]
How are you using it at moment, just MQTT or is it via HA ?

**Comment by irzayev** [comment]
> How are you using it at moment, just MQTT or is it via HA ?

HA

**Comment by liaan** [comment]
The Heat mode should turn the system on .

I don't see any command that just turn unit  "on". there is a "off", but all the rest sets the mode and switch it on.

so bit confused on how you switching the unit on without setting the mode at same time ?


```
def set_homeassistant_mode(self,status):
		if type(status) is not str:
			self.logger.debug('Status variable is not string %s',type(status))
			return False
		
		if status.lower() == 'cool':
			self.status['mode'] = self.STATIC.MODE.COOLING
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)
		elif status.lower() == 'heat':
			self.status['mode'] = self.STATIC.MODE.HEATING
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)
	  
		elif status.lower() == 'auto':
			self.status['mode'] = self.STATIC.MODE.AUTO
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)
		
		if status.lower() == 'dry':
			self.status['mode'] = self.STATIC.MODE.DRY
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)
		if status.lower() == 'fan_only':
			self.status['mode'] = self.STATIC.MODE.FAN
			self.status['power'] =  self.STATIC.ONOFF.ON
			self.set_ac_status()
			return self.make_nice_status(self.status)
		elif status.lower() == "off":
			self.status['power'] =  self.STATIC.ONOFF.OFF
			self.set_ac_status()
			return self.make_nice_status(self.status)
		else:
			self.logger.debug('Invalid status for homekit %s',status)
			return False

	  ```

**Comment by irzayev** [comment]
Actually there is integration of my HA with Yandex Alisa,
In alisa there is Turn On and Turn Off toggle
It seems that there is problem that yandex alisa sends wrong command, but there is no configuration. Thats why I think that there is something with last mode....  

Log from HA when I'm asking Alisa to turn on AC: changed to Heat triggered by service climate.turn_on

**Comment by toyomsk** [comment]
> Actually there is integration of my HA with Yandex Alisa, In alisa there is Turn On and Turn Off toggle It seems that there is problem that yandex alisa sends wrong command, but there is no configuration. Thats why I think that there is something with last mode....
> 
> Log from HA when I'm asking Alisa to turn on AC: changed to Heat triggered by service climate.turn_on

Алисе можно сказать "Включи кондиционер на охлаждение"

**Comment by cipacda** [comment]
I also see this behaviour, when I call .turn_on in HA, it starts the AC in heat mode, although last state was cool.

**Comment by liaan** [comment]
Hi, 

confused.. there is no Turn ON in the HA setup?   only heat/cool/fan/off etc as per above.    ?

see https://github.com/liaan/broadlink_ac_mqtt/blob/master/broadlink_ac_mqtt/AcToMqtt.py  line ~170 is HA setup.

**Comment by liaan** [comment]
Wondering if HA does not do a "intelegence" thing and try guess which mode need to go into, if current temp is lower than target, then go into Heat mode?

**Comment by cipacda** [comment]
I am using this using this add-on, based on this solution: https://github.com/Arbuzov/hass-broadlink-ac-mqtt. 

Turn on is the service from HA to turn the climate on: https://www.home-assistant.io/integrations/climate/#service-climateturn_on

**Comment by liaan** [comment]
Does it work just using the MQTT HA auto config method?

**Comment by cipacda** [comment]
The devices were not auto discovered if that's what you mean, I had to configure them manually.

**Comment by liaan** [comment]
Read the Readme file under https://github.com/liaan/broadlink_ac_mqtt#home-assistant-wwwhome-assistantio-options

That method
